version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/docker_deploy"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/warehouse-postgres-docker"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/warehouse-mcp"
    schedule:
      interval: "weekly"
