from setuptools import find_packages, setup

setup(
    name="orpheus_engine",
    packages=find_packages(exclude=["orpheus_engine_tests"]),
    install_requires=[
        "dagster",
        "dagster-cloud",
        "dagster-postgres",
        "psycopg2-binary",
        "python-dotenv",
        "dagster-embedded-elt",
        "polars",
        "requests",
        "dagster-dlt",
        "dlt[postgres]",
        "googlemaps",
        "litellm>=1.66.1",
        "pyairtable",
        "dagster-docker",
        "dagster-aws",
        "dagster-webserver>=1.10.10",
        "dagster-sling",
        "dagster-dbt",
        "dbt-core>=1.7.0,<2.0.0",
        "dbt-postgres>=1.7.0,<2.0.0",
        "PyYAML",
    ],
    extras_require={"dev": ["dagster-webserver", "pytest"]},
)
