version: 2

sources:
  - name: hackatime_raw
    schema: hackatime
    tables:
      - name: heartbeats
        description: "Raw heartbeat data replicated from the Hackatime production database by Sling."
        meta: { dagster: { asset_key: ['hackatime_warehouse_mirror'] } }

  - name: hackatime_legacy_raw
    schema: hackatime_legacy
    tables:
      - name: heartbeats
        description: "Raw heartbeat data replicated from the Hackatime Legacy database by Sling."
        meta: { dagster: { asset_key: ['hackatime_legacy_warehouse_mirror'] } }

  - name: loops
    schema: loops
    tables:
      - name: audience
        description: "Loops audience data loaded into warehouse via DLT"
        meta: { dagster: { asset_key: ['loops_audience'] } }

  - name: hcb
    schema: hcb
    tables:
      - name: users
        description: "HCB users table (warehouse mirror)."
        meta: { dagster: { asset_key: ['hcb_warehouse_mirror'] } }
      - name: user_seen_at_histories
        description: "HCB user session windows (period_start_at/period_end_at)."
        meta: { dagster: { asset_key: ['hcb_warehouse_mirror'] } }

  - name: slack
    schema: slack
    tables:
      - name: member_analytics_csv
        description: "Slack member analytics data from CSV export."
        meta: { dagster: { asset_key: ['slack_member_analytics_csv'] } }
      - name: member_analytics
        description: "Slack member analytics data."
        meta: { dagster: { asset_key: ['slack_member_analytics'] } }

  # Absolute minimum permissions - only columns needed to generate events for monthly active stats
  - name: auth
    schema: auth
    tables:
      - name: activities
        description: "Auth activity log (logins, profile updates, etc.). Minimal columns only."
        meta: { dagster: { asset_key: ['auth_warehouse_mirror'] } }
      - name: identities
        description: "Auth identities - only id and primary_email accessible."
        meta: { dagster: { asset_key: ['auth_warehouse_mirror'] } }
      - name: oauth_access_tokens
        description: "OAuth access tokens - only id, application_id, resource_owner_id accessible."
        meta: { dagster: { asset_key: ['auth_warehouse_mirror'] } }
      - name: oauth_applications
        description: "OAuth applications - only id, name, trust_level accessible."
        meta: { dagster: { asset_key: ['auth_warehouse_mirror'] } }
