version: 2

sources:
  - name: hackatime_raw
    schema: hackatime
    tables:
      - name: heartbeats
        description: "Raw heartbeat data replicated from the Hackatime production database by Sling."
        meta: { dagster: { asset_key: ['hackatime_warehouse_mirror'] } }

  - name: hackatime_legacy_raw
    schema: hackatime_legacy
    tables:
      - name: heartbeats
        description: "Raw heartbeat data replicated from the Hackatime Legacy database by Sling."
        meta: { dagster: { asset_key: ['hackatime_legacy_warehouse_mirror'] } }

  - name: loops
    schema: loops
    tables:
      - name: audience
        description: "Loops audience data loaded into warehouse via DLT"
        meta: { dagster: { asset_key: ['loops_audience'] } }

  - name: hcb
    schema: hcb
    tables:
      - name: users
        description: "HCB users table (warehouse mirror)."
        meta: { dagster: { asset_key: ['hcb_users'] } }
      - name: user_seen_at_histories
        description: "HCB user session windows (period_start_at/period_end_at)."
        meta: { dagster: { asset_key: ['hcb_user_seen_at_histories'] } }

  - name: slack
    schema: slack
    tables:
      - name: member_analytics_csv
        description: "Slack member analytics data from CSV export."
        meta: { dagster: { asset_key: ['slack_member_analytics_csv'] } }