#!/usr/bin/env bash
# =============================================================================
# DuckLake Common Functions
# =============================================================================
# Shared code for DuckLake scripts. Source this file, don't run it directly.
#
# Exports:
#   - DUCKLAKE_INIT_SQL: Path to generated init SQL file
#   - ducklake_setup: Function to load env and create init SQL
#   - ducklake_cleanup: Function to clean up temp files
# =============================================================================

# Determine paths
DUCKLAKE_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DUCKLAKE_PROJECT_ROOT="$(dirname "$DUCKLAKE_SCRIPT_DIR")"
DUCKLAKE_ENV_FILE="$DUCKLAKE_PROJECT_ROOT/.env"

# Temp file for init SQL (set by ducklake_setup)
DUCKLAKE_INIT_SQL=""

# Load .env file and export DUCKLAKE_* variables
ducklake_load_env() {
    if [[ ! -f "$DUCKLAKE_ENV_FILE" ]]; then
        echo "❌ Error: .env file not found at $DUCKLAKE_ENV_FILE"
        echo ""
        echo "Create a .env file with the following variables:"
        echo "  DUCKLAKE_CATALOG_DB_URL=postgres://user:pass@host:port/db?sslmode=require"
        echo "  DUCKLAKE_S3_KEY_ID=your_key_id"
        echo "  DUCKLAKE_S3_SECRET=your_secret"
        echo "  DUCKLAKE_S3_URL=https://xxx.r2.cloudflarestorage.com"
        return 1
    fi

    # Read .env line by line, handling special characters
    while IFS= read -r line || [[ -n "$line" ]]; do
        # Skip comments and empty lines
        [[ -z "$line" || "$line" =~ ^[[:space:]]*# ]] && continue
        # Only process lines with = (key=value format)
        if [[ "$line" =~ ^([A-Za-z_][A-Za-z0-9_]*)=(.*)$ ]]; then
            key="${BASH_REMATCH[1]}"
            value="${BASH_REMATCH[2]}"
            # Only export DUCKLAKE vars
            if [[ "$key" == DUCKLAKE_* ]]; then
                export "$key=$value"
            fi
        fi
    done < "$DUCKLAKE_ENV_FILE"
}

# Validate required environment variables
ducklake_validate_env() {
    local required_vars=(
        "DUCKLAKE_CATALOG_DB_URL"
        "DUCKLAKE_S3_KEY_ID"
        "DUCKLAKE_S3_SECRET"
        "DUCKLAKE_S3_URL"
    )

    local missing_vars=()
    for var in "${required_vars[@]}"; do
        if [[ -z "${!var:-}" ]]; then
            missing_vars+=("$var")
        fi
    done

    if [[ ${#missing_vars[@]} -gt 0 ]]; then
        echo "❌ Error: Missing required environment variables:"
        for var in "${missing_vars[@]}"; do
            echo "  - $var"
        done
        return 1
    fi
}

# Parse postgres:// URL to libpq format
# Input: postgres://user:pass@host:port/db?sslmode=require
# Output: dbname=db host=host port=port user=user password=pass sslmode=require
ducklake_parse_postgres_url() {
    local url="$1"
    
    # Remove postgres:// or postgresql:// prefix
    local rest="${url#postgres://}"
    rest="${rest#postgresql://}"
    
    # Extract user:pass
    local userpass="${rest%%@*}"
    local user="${userpass%%:*}"
    local pass="${userpass#*:}"
    
    # Extract host:port/db?params
    rest="${rest#*@}"
    local hostport="${rest%%/*}"
    local host="${hostport%%:*}"
    local port="${hostport#*:}"
    
    # Extract db and params
    rest="${rest#*/}"
    local db="${rest%%\?*}"
    local params=""
    if [[ "$rest" == *"?"* ]]; then
        params="${rest#*\?}"
    fi
    
    # Build libpq format
    local libpq="dbname=$db host=$host port=$port user=$user password=$pass"
    if [[ -n "$params" && "$params" == *"sslmode="* ]]; then
        local sslmode="${params#*sslmode=}"
        sslmode="${sslmode%%&*}"
        libpq="$libpq sslmode=$sslmode"
    fi
    
    echo "$libpq"
}

# Create the init SQL file for DuckLake connection
ducklake_create_init_sql() {
    local include_ui="${1:-false}"
    
    # Parse S3 endpoint (strip protocol)
    local s3_endpoint="${DUCKLAKE_S3_URL#https://}"
    s3_endpoint="${s3_endpoint#http://}"
    s3_endpoint="${s3_endpoint%/}"
    
    # Parse postgres URL
    local libpq_conn
    libpq_conn=$(ducklake_parse_postgres_url "$DUCKLAKE_CATALOG_DB_URL")
    
    # Create temp file (capture output to avoid printing path)
    DUCKLAKE_INIT_SQL=$(mktemp /tmp/ducklake_init.XXXXXX.sql)
    export DUCKLAKE_INIT_SQL
    
    cat > "$DUCKLAKE_INIT_SQL" << EOF
-- DuckLake Initialization
-- Auto-generated by ducklake scripts

-- Install required extensions
INSTALL ducklake;
INSTALL postgres;
INSTALL httpfs;

-- Load extensions
LOAD ducklake;
LOAD postgres;
LOAD httpfs;

-- Configure S3 credentials (Cloudflare R2 / S3-compatible)
CREATE OR REPLACE SECRET ducklake_s3 (
    TYPE S3,
    KEY_ID '${DUCKLAKE_S3_KEY_ID}',
    SECRET '${DUCKLAKE_S3_SECRET}',
    ENDPOINT '${s3_endpoint}',
    USE_SSL true,
    URL_STYLE path,
    SCOPE 's3://'
);

-- Attach DuckLake with PostgreSQL catalog
ATTACH 'ducklake:postgres:${libpq_conn}' AS warehouse_ducklake;

-- Use the DuckLake database by default
USE warehouse_ducklake;

-- Increase retry count for reliability
SET ducklake_max_retry_count = 100;

-- Ready message
SELECT '✅ DuckLake connected! Database: warehouse_ducklake' AS status;
EOF

    # Add UI setup if requested
    if [[ "$include_ui" == "true" ]]; then
        cat >> "$DUCKLAKE_INIT_SQL" << 'EOF'

-- Load and start UI server
INSTALL ui;
LOAD ui;
SET ui_local_port = 4213;
CALL start_ui_server();
EOF
    fi
}

# Cleanup function
ducklake_cleanup() {
    if [[ -n "$DUCKLAKE_INIT_SQL" && -f "$DUCKLAKE_INIT_SQL" ]]; then
        rm -f "$DUCKLAKE_INIT_SQL"
    fi
}

# Main setup function - call this from scripts
# Usage: ducklake_setup [--ui]
ducklake_setup() {
    local include_ui="false"
    if [[ "${1:-}" == "--ui" ]]; then
        include_ui="true"
    fi
    
    # Load and validate environment
    ducklake_load_env || return 1
    ducklake_validate_env || return 1
    
    # Create init SQL
    ducklake_create_init_sql "$include_ui"
    
    # Set up cleanup trap
    trap ducklake_cleanup EXIT
    
    # Print connection info
    local s3_endpoint="${DUCKLAKE_S3_URL#https://}"
    s3_endpoint="${s3_endpoint#http://}"
    s3_endpoint="${s3_endpoint%/}"
    
    echo "🦆 DuckLake Connection"
    echo "   Catalog: ${DUCKLAKE_CATALOG_DB_URL%%:*}://...@${DUCKLAKE_CATALOG_DB_URL#*@}"
    echo "   S3: $s3_endpoint"
    echo ""
}

