# -*- coding: utf-8 -*-
# Generated by scripts/generate_airtable_ids.py. DO NOT EDIT MANUALLY.
# fmt: off

class AirtableIDs:
    """Container for generated Airtable Base, Table, and Field IDs."""

    class analytics_hack_clubbers:
        """IDs for Base 'analytics_hack_clubbers' (ID: appCGB6LccMzwkJZg)"""
        BASE_ID = "appCGB6LccMzwkJZg"

        class hack_clubbers:
            """IDs for Table 'hack_clubbers' (ID: tbluKHJi8hmg34uOF)"""
            TABLE_ID = "tbluKHJi8hmg34uOF"

            email = "fldPdy8PS8thWiO9e"  # Name: Email
            last_engagement_at = "fldR8L8CYXHOFqeXY"  # Name: Last Engagement At
            first_engagement_at = "flda4pqoaBcXthgVC"  # Name: First Engagement At
            first_engagement = "fldL2V98044JP2490"  # Name: First Engagement
            first_program = "fld0hbEmhMnlWTXxD"  # Name: First Program
            second_program = "fldPd7TRGEn4GNMIr"  # Name: Second Program
            first_name = "fldkCpESmYzhzszgD"  # Name: First Name
            last_name = "fldAkYYr1KPlT8Shg"  # Name: Last Name
            git_hub_username = "fldo3ijhoImccYWF1"  # Name: GitHub Username
            address_line_1 = "fldxz5WmFmTRAA8Uh"  # Name: Address Line 1
            address_line_2 = "fldQBRXGkwiTjE5Gk"  # Name: Address Line 2
            city = "fldYLQ9OQrKrpPreo"  # Name: City
            state = "fldLGhFMu4MNB7tbf"  # Name: State
            zip = "fldngtbpJA6Ki1XhT"  # Name: ZIP
            country = "fldqqoqqaX8Np6wec"  # Name: Country
            address_last_updated_at = "fldpgpL2L8avgJaSe"  # Name: Address Last Updated At
            programs = "fld6SNyJDuuaoDi02"  # Name: Programs
            last_engagement = "fldPsX86QczIT72xk"  # Name: Last Engagement
            total_engagements = "fldWYqRUOghaQ3AeG"  # Name: Total Engagements
            engagements_overview = "fldVPcRzBgat57RII"  # Name: Engagements Overview
            ship_count = "fldXDOr6f8UpEq2DF"  # Name: #ship count
            last_ship = "fldZ3wDpW7kRb1wtM"  # Name: Last #ship
            scrapbook_count = "fldMioUornccdgITA"  # Name: #scrapbook count
            last_scrapbook = "fldt1HbbtAPeHK5rh"  # Name: Last #scrapbook
            last_ysws_approved_at = "fldPCTdWTYBv95NXp"  # Name: Last YSWS Approved At
            last_ysws_approved = "fldaLkyCbE77obm45"  # Name: Last YSWS Approved
            ysws_approved_count = "fldckIW9hNmzW49Xk"  # Name: YSWS Approved Count
            ysws_weighted_grant_contribution = "fld7QYT7jIjUfWfwN"  # Name: YSWS Weighted Grant Contribution
            ysws_2025_weighted_grant_contribution = "fldMhjnyHcj95xAs9"  # Name: YSWS 2025 Weighted Grant Contribution
            ysws_weighted_grant_last_updated_at = "fldtasV6W8rMJ3Kxd"  # Name: YSWS Weighted Grant # Last Updated At
            ysws_first_stated_referral_reason = "fldw4NFCsgiFD2SZI"  # Name: YSWS First Stated Referral Reason
            ysws_first_stated_referral_category = "fldAkhtAHaM4nyuTJ"  # Name: YSWS First Stated Referral Category
            last_shipment_at = "fld9rYry1A4y5639q"  # Name: Last Shipment At
            last_shipment_contents = "fld6zA426vjcPgF6R"  # Name: Last Shipment Contents
            birthday = "fldT43iLDNGVLMbaG"  # Name: Birthday
            current_age = "fldVmL8HMrXuV5pZa"  # Name: Current Age
            search_field = "fldtFEnuqg8R3gwQy"  # Name: Search Field
            gender = "fldVuy6Bc3Ww1j9fH"  # Name: Gender
            slack_id = "fldV55ApIRoRXEWne"  # Name: Slack ID
            longitude = "fldl9sWFfdCAVeItF"  # Name: Longitude
            latitude = "fld6JDgRLSPq8Lp2v"  # Name: Latitude
            geocoded_country = "fldkoQz2PXvI02kOD"  # Name: Geocoded Country
            phone_number = "fldlLCvLTuQCKHUNd"  # Name: Phone Number
            create_shipment = "fldrjbBU9ki5rf3DH"  # Name: create shipment!

        class field_mapping_rules:
            """IDs for Table 'field_mapping_rules' (ID: tbl7SkwqGYtFl4pe4)"""
            TABLE_ID = "tbl7SkwqGYtFl4pe4"

            loops_so_field_to_map = "fldnjsCqhetjq4wBh"  # Name: Loops.so Field To Map
            hack_clubber_field = "fldd3p4ZDWIjjkdKt"  # Name: Hack Clubber Field

        class program_mapping_rules:
            """IDs for Table 'program_mapping_rules' (ID: tbl02flnwdqn8NcgG)"""
            TABLE_ID = "tbl02flnwdqn8NcgG"

            loops_so_field_to_map = "fldgtnrn7tq1dNjDT"  # Name: Loops.so Field To Map
            program = "fld6xM9D8pPFankEB"  # Name: Program

        class programs:
            """IDs for Table 'programs' (ID: tblo0e0B4UQ4edi31)"""
            TABLE_ID = "tblo0e0B4UQ4edi31"

            name = "fldYqdE55u9NgTpTd"  # Name: Name
            hcers_brought_in_who_did_a_ysws_this_month = "fldEvQDo61AbZ30wa"  # Name: HCers brought in who did a YSWS this month
            hcers_brought_in_who_did_a_ysws_this_year = "fldNp5rctO7BBiLQq"  # Name: HCers brought in who did a YSWS this year
            hcers_brought_in_this_month = "fldmjKOYaauHTf25p"  # Name: HCers brought in this month
            hcers_brought_in_this_year = "fldbhLElo2h9l0Dnl"  # Name: HCers brought in this year
            hcers_brought_in_this_year_who_have_engaged_in_a_2nd_program = "fldg5PKX47u5c3ErV"  # Name: HCers brought in this year who have engaged in a 2nd program
            mapping_rules = "fldAWCJQoAQ6e4z2x"  # Name: Mapping Rules
            participating_hack_clubbers = "fldofIaFiFbHYGpW8"  # Name: Participating Hack Clubbers
            hack_clubbers_brought_in_by_program = "fldiG1J2xgqa8lSLL"  # Name: Hack Clubbers Brought In By Program
            hack_clubbers_with_this_program_as_their_2nd_engagement = "fld8bY4axzv7hmwDA"  # Name: Hack Clubbers With This Program As Their 2nd Engagement


    class neighborhood:
        """IDs for Base 'neighborhood' (ID: appnsN4MzbnfMY0ai)"""
        BASE_ID = "appnsN4MzbnfMY0ai"

        class neighbors:
            """IDs for Table 'neighbors' (ID: tblTGpK7QgwsqT8t0)"""
            TABLE_ID = "tblTGpK7QgwsqT8t0"

            email = "flduN2BlNtozsp5xZ"  # Name: email
            total_time_hackatime_hours = "fldgawsm3YG4b2C5V"  # Name: totalTimeHackatimeHours
            total_time_stopwatch_hours = "fldD8IywF8keOhSJd"  # Name: totalTimeStopwatchHours
            total_time_combined_hours = "fldQmyJBIHfmAp73d"  # Name: totalTimeCombinedHours
            full_name = "fldF7r89RpZ0WsaW4"  # Name: Full Name
            date_of_birth = "fldOygvFVgwArnj36"  # Name: Date of Birth
            token = "fldTMjrUrqTflOGBx"  # Name: token
            sessions = "fld1HC2XIHKk29AQe"  # Name: sessions
            github_username = "fldjw0OdVL7EN9521"  # Name: githubUsername
            commits = "fldiV80pumQcuswPo"  # Name: commits
            invites = "flduLNKHWAqsMCQ5Y"  # Name: invites
            slack_neighbor = "fld3fOnOAo22kPq3c"  # Name: slackNeighbor
            pfp_from_slack_neighbor = "fldv0qc5jSXftaxxt"  # Name: Pfp (from slackNeighbor)
            slack_id_from_slack_neighbor = "fldtGzNkSmENJ4dZM"  # Name: Slack ID (from slackNeighbor)
            slack_handle_from_slack_neighbor = "fldS8nY4J5k6RqJOG"  # Name: Slack Handle (from slackNeighbor)
            full_name_from_slack_neighbor = "fldh3GA2DutgIRvZ4"  # Name: Full Name (from slackNeighbor)
            created_at = "fldHX2x94MK0eCZz5"  # Name: createdAt
            has_hackatime_at = "fldBB56XVkvKAzFN8"  # Name: hasHackatimeAt
            github_project = "fldKPKw7ZtnshB7Qo"  # Name: githubProject
            project_description = "fldzCQ2BmS7kkOpa9"  # Name: projectDescription
            project_name = "fldjBwy9h7Aixt40D"  # Name: projectName
            hackatime_projects = "fldwulpnDLhKQP8Qi"  # Name: hackatimeProjects
            loops_special_set_full_name = "fldtoOwj09ywVl6of"  # Name: Loops - Special - setFullName
            loops_neighborhood_sign_up_at = "fldud54x3An7UBqXW"  # Name: Loops - neighborhoodSignUpAt
            loops_birthday = "fldulwgHvMeu4kIFQ"  # Name: Loops - birthday
            loops_neighborhood_has_hackatime_at = "fldMNOI6mgpffAEyW"  # Name: Loops - neighborhoodHasHackatimeAt
            zapier_added_to_neighborhood_mailing_list_at = "fldOvjuA3x1UF3clq"  # Name: Zapier - Added to Neighborhood mailing list at
            apps = "fldgP54dgV9BYOOUD"  # Name: Apps
            devlog = "fldijYi51GpUlaOJk"  # Name: devlog
            total_checked_time = "fldEy1busms5l0z16"  # Name: totalCheckedTime
            total_time_hackatime_seconds = "fldoWMncGnNk7PkZe"  # Name: totalTimeHackatimeSeconds
            total_time_stopwatch_minutes = "fldIXiD6QzBKg0q4V"  # Name: totalTimeStopwatchMinutes
            hack_clubber = "fldzsY67bxOBzpF2U"  # Name: Hack Clubber
            gender_from_hack_clubber = "fldYuNPOiE9BZTDWB"  # Name: Gender (from Hack Clubber)
            first_engagement_from_hack_clubber = "fldmHCJ4LEFrCUgLr"  # Name: First Engagement (from Hack Clubber)
            first_engagement_at_from_hack_clubber = "fldOeJoYxsqUVrags"  # Name: First Engagement At (from Hack Clubber)
            email_from_hack_clubber = "fldynlPE3lSYTNoPn"  # Name: Email (from Hack Clubber)
            ysws_project_submission_from_apps = "fldCCqeLZ98QGjuNz"  # Name: YSWS Project Submission (from Apps)
            move_in_date = "fldvl9C0PdGB4rCSJ"  # Name: move-in-date
            move_out_date = "flddD3Uq93uS3SoT4"  # Name: move-out-date
            rooms = "fld1CRYR8fm1gWfeI"  # Name: Rooms
            room_gender = "fldmqxYDLp98zdpMC"  # Name: RoomGender
            comments = "fldtiQ5qz93Pg2eHU"  # Name: Comments
            total_days = "fldSO66JuHbuhkQKr"  # Name: total-days
            visa_home_assignments = "fldmTtg5U8BmPQXlO"  # Name: VisaHomeAssignments
            age_at_sign_up = "fldzuo4LvG4l1ayDr"  # Name: Age At Sign-Up
            age_eligible_at = "fld6k4njoQS3nmo1o"  # Name: ageEligibleAt
            time_over1_hour = "fldvcDJtToZy3MmiE"  # Name: timeOver1Hour
            time_over25_hours = "fldAjUL5ho3DvMqhg"  # Name: timeOver25Hours
            time_over50_hours = "fldBB0vqfHjHFwyyB"  # Name: timeOver50Hours
            time_over75_hours = "fldqHEpIypRvxH3bL"  # Name: timeOver75Hours
            time_over100_hours = "fldNmKOC1UmhuUCmu"  # Name: timeOver100Hours
            ysws_project_submitted_at = "fldjgX1MI2N6JwULl"  # Name: yswsProjectSubmittedAt
            granted_hours = "fldpbGt3d43j9nUYW"  # Name: GrantedHours
            ysws_project_submitted_staff_approved = "fldoBkA3lrmvtFoyX"  # Name: yswsProjectSubmittedStaffApproved
            country = "fldodb9BuLa4ApYbN"  # Name: country
            airport = "fldzzTahGopPmDTkl"  # Name: airport
            has_visa = "fldAuoDvTz3IH4i3h"  # Name: hasVisa
            unreviewed_devlog_count = "fldFEHEfibio3eiQ1"  # Name: unreviewedDevlogCount
            ysws_project_submission = "fldWLN24iL2P4awTX"  # Name: YSWS Project Submission
            ysws_project_submission_copy = "fld64FAjNTpT18NHi"  # Name: YSWS Project Submission copy
            ysws_project_submission_copy = "fldncW9I2k7DEelDT"  # Name: YSWS Project Submission copy

        class hackatime_projects:
            """IDs for Table 'hackatime_projects' (ID: tblIqliBgKvoNT3uD)"""
            TABLE_ID = "tblIqliBgKvoNT3uD"

            id_auto = "fld5AIb2Hce93a7no"  # Name: idAuto
            name = "fldxfUM1hVmUp9wcG"  # Name: name
            email = "flddVY9cveGbXqP6K"  # Name: email
            commits = "fldCiY5HxO6yvVvWo"  # Name: commits
            description = "fld0s3MW3Q77mr53z"  # Name: description
            neighbor = "fldYgoiBlHUMElnYK"  # Name: neighbor
            github_link = "fldLTbhfMJVYPVjB7"  # Name: githubLink
            invites = "fld8TaHXV4Ev8cUm6"  # Name: invites
            created_at = "fldl0zGygN16MWynk"  # Name: createdAt
            sessions = "fld9d6sivClb6GIwa"  # Name: sessions
            apps = "fldSJ8ltjI8CMNUyy"  # Name: Apps
            name_from_apps = "fldAl407aK8q34z5r"  # Name: Name (from Apps)
            calcul = "fld1RndPLnMvmD7zf"  # Name: Calcul
            slack_id = "fldDu4An1KY5utXC1"  # Name: slackId
            total_time = "fldqSsiI9hZb2OW9g"  # Name: totalTime
            total_time_hours = "fldILpudcwm5io04z"  # Name: totalTimeHours
            more_than_one_user = "fldlPV7I6oORuOIj1"  # Name: moreThanOneUser
            created = "fld7SuT6aT0AUGGyC"  # Name: Created
            ysws_project_submission_from_apps = "fldYOwYZ57sL0r4DE"  # Name: YSWS Project Submission (from Apps)


    class shipwrecked:
        """IDs for Base 'shipwrecked' (ID: appcfQcNlm6vXUOad)"""
        BASE_ID = "appcfQcNlm6vXUOad"

        class rsvps:
            """IDs for Table 'rsvps' (ID: tblGW44enlxcYjDjS)"""
            TABLE_ID = "tblGW44enlxcYjDjS"

            email = "fldHtR3taM8g8CWXC"  # Name: Email
            first_name = "fldZx3qAINejnw3iU"  # Name: First Name
            last_name = "fldbrTWeaFL8qwwUK"  # Name: Last Name
            birthday = "fldbnLqZdBx5kHXIY"  # Name: Birthday
            current_age = "fld4F4Ku4wXE3PNFL"  # Name: Current Age
            loops_first_name = "fldK8GsyirxyStpWH"  # Name: Loops - firstName
            loops_last_name = "fldIeNq9sxBpeSsjz"  # Name: Loops - lastName
            loops_birthday = "fldg2PDzyVgntfhdt"  # Name: Loops - birthday
            loops_shipwrecked_sign_up_at = "fldpFp794BweHvxWN"  # Name: Loops - shipwreckedSignUpAt
            zapier_added_to_shipwrecked_loops_mailing_list_at = "fldtjf0WgIPkxARkk"  # Name: Zapier - Added to Shipwrecked Loops mailing list at
            referral_code = "fld5DXnUQLxcjn2Xk"  # Name: referral_code
            referral_type = "fldOlvpXGZfaKQEN7"  # Name: referral_type
            loops_shipwrecked_sign_up_position = "fld2qb4DViP6e9N4b"  # Name: Loops - shipwreckedSignUpPosition
            ip_address = "fldFAELbzAbzqxjK8"  # Name: IP Address
            country = "fldS7C8f2BqUmL1Fw"  # Name: Country
            participants_referred = "fld1KMBVLjJtxMtmZ"  # Name: Participants Referred
            number_of_referrals = "fldV0f6k0kjNhdDQJ"  # Name: Number of Referrals
            disqualified_from_raffle = "fld9MCo0sAfuEXYii"  # Name: Disqualified_from_raffle
            add_to_slack = "fldtTt0CoXuqWdiSU"  # Name: AddToSlack?
            created_at = "fldxZBl3Y92B7icVV"  # Name: createdAt
            age_eligible_at = "fld8tatAv1Syhf8Kp"  # Name: ageEligibleAt
            has_hackatime_at = "fldO4HAkyTTRiraKG"  # Name: hasHackatimeAt
            logged_first_hour = "fldOZcXpk5ZUtocmZ"  # Name: loggedFirstHour
            logged_ten_hours = "fldEUzm2kzocxUA8S"  # Name: loggedTenHours
            submitted_first_project = "fld3Mu3BoCktJIdcw"  # Name: submittedFirstProject
            first_project_approved = "fldSWTtuYyq7jnRTq"  # Name: firstProjectApproved
            logged_first_hour_on_second_project = "fldj7etQaidqXuc6K"  # Name: loggedFirstHourOnSecondProject
            submitted_second_project = "fldbw0lZyl92GxlBh"  # Name: submittedSecondProject
            second_project_approved = "fldoGN2NW6jMhh0Nv"  # Name: secondProjectApproved
            logged_first_hour_on_third_project = "fldfIN0aJJ6H75GCs"  # Name: loggedFirstHourOnThirdProject
            submitted_third_project = "fldeLt3MnwE2lm6UY"  # Name: submittedThirdProject
            third_project_approved = "fld7CXYUG2yDdvZ7t"  # Name: thirdProjectApproved
            logged_first_hour_on_fourth_project = "fldAqWBiXsIvCh3Vt"  # Name: loggedFirstHourOnFourthProject
            submitted_fourth_project = "fldkJCAM5lHwt5xyK"  # Name: submittedFourthProject
            fourth_project_approved = "fldQnuIrqn0Dy17Jd"  # Name: fourthProjectApproved
            user_exists_in_bay = "fldm1Ns9lKIaJNvnE"  # Name: userExistsInBay
            total_raw_hackatime_hours = "fld1tdBSSLKnKOo0D"  # Name: totalRawHackatimeHours
            total_approved_hackatime_hours = "fldJ1OC5ibU6vJe8t"  # Name: totalApprovedHackatimeHours
            created = "fldePoj75HS2SGHQb"  # Name: Created
            non_disqualified_referrals = "fldHKZkydQU1p0tjO"  # Name: Non-Disqualified Referrals
            number_of_referrals_18 = "fldSux7TS7q9ZxLEK"  # Name: Number of Referrals <=18
            hack_clubber = "fldCPXnlvgkO8QEPc"  # Name: Hack Clubber
            hack_clubber_first_engagement = "fldYeV8CZYpqEEiw2"  # Name: Hack Clubber – First Engagement
            hack_clubber_ysws = "fldBfLG18FaRMtIbX"  # Name: Hack Clubber – YSWS
            rsvps_last_24h = "fldDhIqWDBfRFVTvs"  # Name: rsvps_last_24h
            created_at = "fldgz5xzYbF7TORKE"  # Name: Created At
            loops_shipwrecked_user_exists_in_bay = "fldvXPNRWtyLALtIo"  # Name: Loops - shipwreckedUserExistsInBay


    class highway:
        """IDs for Base 'highway' (ID: appuDQSHCdCHyOrxw)"""
        BASE_ID = "appuDQSHCdCHyOrxw"

        class rsvps:
            """IDs for Table 'rsvps' (ID: tblhGTc3WX9nYzU18)"""
            TABLE_ID = "tblhGTc3WX9nYzU18"

            email = "flduP5J737EBLvvbk"  # Name: email
            invited_to_slack = "fldkfyVH8J1qkmZbO"  # Name: invited_to_slack
            welcome_message_sent = "fldFIleT1Rf1B8b5N"  # Name: welcome_message_sent
            dm_error = "flduZHuUw19rIajXp"  # Name: dm_error
            birthday = "fldJRYzfImVmNeS9c"  # Name: birthday
            sticker_request_birthday = "fldud8kjykhWtjApx"  # Name: sticker_request_birthday
            available_birthday = "fldneqipow42yzySz"  # Name: available_birthday
            sticker_request = "fldMVkYiW3NNW4qNX"  # Name: sticker_request
            age = "fldTHAuLbNyDCYDdr"  # Name: age
            source = "fldSaQbhApCRWu1Mz"  # Name: source
            url_params = "fldDn8Y6HWI9Ekqll"  # Name: url_params
            loops_highway_pre_rsvp_at = "fldWlrEOmkdRFj7Hl"  # Name: Loops - highwayPreRsvpAt
            record_id = "fldYojFZSkbcUw43e"  # Name: Record ID
            created_at = "fldqIVKU2PGwXhqzJ"  # Name: Created At
            send_github_email = "fldhhfdejpkQMbLoL"  # Name: send_github_email
            was_at_kickoff = "fldVpS0j4d1cOT0MH"  # Name: was at kickoff


    class athena_award:
        """IDs for Base 'athena_award' (ID: appwSxpT4lASsosUI)"""
        BASE_ID = "appwSxpT4lASsosUI"

        class registered_users:
            """IDs for Table 'registered_users' (ID: tblIk0A5f9eqSng1h)"""
            TABLE_ID = "tblIk0A5f9eqSng1h"

            email = "fld0TaaawpieJ9G2A"  # Name: email
            role = "fldQWhQF9Jdo8Sb6Y"  # Name: role
            slack_id = "fldDAgtj5tJnuK6cm"  # Name: slack_id
            track = "fldduIOpBro5oKbdL"  # Name: track
            display_name = "flda5W7GQQ3hoRWEr"  # Name: display_name
            self_reported_partners_from_email_slack_invites = "fldBsOjnM2x6nd9nP"  # Name: self_reported_partners (from Email Slack Invites)
            self_reported_partners_onboarding = "fldYtMpblMK26c6Ns"  # Name: self_reported_partners_onboarding
            points = "fld782uY9yKgq3qcN"  # Name: points
            total_time_approved_projects = "fldFJqzcq3PhqhGz0"  # Name: total_time_approved_projects
            artifacts = "fldxx7cJTdiKZ0fDz"  # Name: artifacts
            hackathon_codes = "fldtdzeYRpQMmaMu5"  # Name: hackathon_codes
            hackathons = "fldqXDbPMxvL98a3i"  # Name: hackathons
            hack_clubbers = "fldaNQTyoCfE7IVFA"  # Name: Hack Clubbers
            record_id = "fldYyDAL5HpFr0mbN"  # Name: record_id
            hashed_token = "fldpTp8vdsryYVte6"  # Name: hashed_token
            registered = "fld7RHGzEfOc5OJJz"  # Name: registered
            projects = "fldBRcF2KqPVJdvdS"  # Name: projects
            duration_from_projects = "fldm6vhWLZOctIlIU"  # Name: duration (from projects)
            ysws_project_submission = "fldXnJWsOhQkl2laW"  # Name: ysws_project_submission
            approved_duration_from_projects = "fldag6JrdejDNjCAS"  # Name: approved_duration (from projects)
            unified_ysws_projects_db = "fldFl0yclGYljU6Wg"  # Name: Unified YSWS Projects DB
            hours_spent_rollup_from_unified_ysws_projects_db = "fldcRUHh4REm4TyOI"  # Name: Hours Spent Rollup (from Unified YSWS Projects DB)
            hackatime_set_up_at = "fld1X9TIKhVgP0P4I"  # Name: hackatime_set_up_at
            orders = "fldxu4NA7YMtY9oHJ"  # Name: Orders
            force_refresh_ysws_projects = "fldRvL6FlJ7RDIwTn"  # Name: force_refresh_ysws_projects
            loops_athena_award_first_logged_in_at = "flducWTMuVh0xpXCP"  # Name: Loops - athenaAwardFirstLoggedInAt
            zapier_added_to_athena_mailing_list_at = "fldQJHbZozaH7MskV"  # Name: Zapier - Added to Athena mailing list at
            referred_users = "fldVqPyWX8ZTuPCAj"  # Name: referred_users
            email_slack_invites = "fldaofojjV18uvAN4"  # Name: Email Slack Invites
            referred_users_account_created = "fldnghkHaGhIKF7o9"  # Name: referred_users_account_created
            referred_users_registered_users_count = "fldl2x5dLU4pxox8N"  # Name: referred_users_registered_users_count
            referred_users_count = "fldKkUQ312lzdgpLD"  # Name: referred_users_count
            referred_users_registered_users_edition = "fld1Bl83LyowhNubP"  # Name: referred_users_registered_users_edition
            profile_picture = "fldxLDUvCXQCDxfnr"  # Name: profile_picture
            project_unique_names = "fldxlzRtJrUWuwyKY"  # Name: project_unique_names
            approved_projects = "fldfQp5eDL8IEeVwH"  # Name: approved_projects
            zach_has_hackatime_or_submitted_athena_project = "fldMz3kFXwonzGVix"  # Name: Zach - has_hackatime_or_submitted_athena_project
            total_number_orders = "flddaNQgUnpAELGqE"  # Name: total_number_orders
            email_slack_invites_copy = "fldiDAliUsDB7EQV3"  # Name: Email Slack Invites copy
            email_slack_invites_copy = "fldxB0bFgfFQ7kO8O"  # Name: Email Slack Invites copy

        class email_slack_invites:
            """IDs for Table 'email_slack_invites' (ID: tblmiCs66Oy9ux6eN)"""
            TABLE_ID = "tblmiCs66Oy9ux6eN"

            email = "fld4z7buJbTKfaNwl"  # Name: email
            self_reported_partners = "fld2W473TCyAId9Eg"  # Name: self_reported_partners
            error = "fldTKFomRhiwIZgPx"  # Name: error
            dm_error = "fldCT4uWXH7orBz7Q"  # Name: dm_error
            welcome_message_sent = "fldol2W6BbcbxPZV8"  # Name: welcome_message_sent
            registered_user = "fldy5QsE0yYmolUpz"  # Name: registered_user
            referred_by = "fldhVLEsJUZvAutKH"  # Name: referred_by
            utm_source = "fldrKkjeJ7DlQ5tid"  # Name: utm_source
            created = "fld3OFPCqwso8TlPX"  # Name: Created
            loops_athena_award_slack_invite_requested_at = "fld7hufACh1X4tp42"  # Name: Loops - athenaAwardSlackInviteRequestedAt
            zapier_added_to_athena_mailing_list_at = "fldGAuFJmK2yb5H3v"  # Name: Zapier - Added to Athena mailing list at

        class free_sticker_form:
            """IDs for Table 'free_sticker_form' (ID: tblBOgmyC9RVK98wD)"""
            TABLE_ID = "tblBOgmyC9RVK98wD"

            email = "fldN19TbrTnCXSngO"  # Name: Email
            first_name = "fldf3tegs4na6q0Yp"  # Name: First Name
            last_name = "fldQjTSwM4Q2CFJwB"  # Name: Last Name
            pronouns = "fldtE2kq4EsjdbIOI"  # Name: Pronouns
            git_hub_username = "fldZ9X0H5Fl2gGID3"  # Name: GitHub Username
            birthday = "fldTEJDYg9Ws6OtqY"  # Name: Birthday
            address_line_1 = "fldQ49GD41UG0gb7Q"  # Name: Address Line 1
            address_line_2 = "fldPXNCo4ckwUf9Hr"  # Name: Address Line 2
            city = "fldHsStlvMorfS9gx"  # Name: City
            state = "fldgk1AAysYHcHrpF"  # Name: State
            zip_postcode = "fldkOjR7CJeRB2EBs"  # Name: ZIP/Postcode 
            country = "flddIqe8RLyOnGKc2"  # Name: Country
            loops_athena_award_stickers_requested_at = "fldVIrRhcFEzcC8vS"  # Name: Loops - athenaAwardStickersRequestedAt
            loops_first_name = "fldEEk4v3I8MlhTQt"  # Name: Loops - firstName
            loops_last_name = "fldWp3vGALPoh24pm"  # Name: Loops - lastName
            loops_gender_self_reported = "fldndV1vBDxKiUGLo"  # Name: Loops - genderSelfReported
            loops_github_username = "fldLCS6Wq52UwkNTI"  # Name: Loops - githubUsername
            loops_special_set_full_address = "fldXckAr3vu1m1MsD"  # Name: Loops - special - setFullAddress
            theseus_letter_id = "fld65tjhaen9iv77b"  # Name: Theseus – Letter ID
            theseus_status = "fldQHZvDCbUMRdHnf"  # Name: Theseus – Status
            theseus_mailed_at = "fldUSdrzjAlXx4w2l"  # Name: Theseus – Mailed At
            theseus_received_at = "fldkxqtBALXfXzBLu"  # Name: Theseus – Received At
            theseus_postage_cost = "fldkAbCFvMOqDFDz2"  # Name: Theseus – Postage Cost
            theseus_create_letter = "fldfszoyV5xqqz2Yl"  # Name: Theseus – Create Letter
            theseus_error = "fldfyIYIf8FYo2s0z"  # Name: Theseus – Error

        class projects:
            """IDs for Table 'projects' (ID: tblZqHeeelwGkOkRr)"""
            TABLE_ID = "tblZqHeeelwGkOkRr"

            record_id = "fldcwoCVYQ9P3GdKv"  # Name: record_id
            unique_name = "fld8A7FjUiOI5Ho8M"  # Name: unique_name
            project_name = "fld6vGpatATHH7rn8"  # Name: project_name
            project_name_override = "fldCodpGWr0hiGisg"  # Name: project_name_override
            guided_ysws = "fld16dhOG3s49vzq5"  # Name: guided_ysws
            automation_guided_ysws = "fldvYjS28P2rnw9H6"  # Name: automation_guided_ysws
            hackatime_duration = "fldiMCjGxVHmafb5f"  # Name: hackatime_duration
            existing_ysws_project_hour_override = "fldYiOsaEbm0oRa8s"  # Name: existing_ysws_project_hour_override
            approved_duration = "fld4eD1QIbHookKrF"  # Name: approved_duration
            stage = "fldDeBwC0YPE69Xl3"  # Name: stage
            status = "fld8mVhD1hOom2i9i"  # Name: status
            registered_user = "fldbWcHEPieWbwaaQ"  # Name: registered_user
            stringified_email = "flddvqww48TLt7JKs"  # Name: stringified_email
            form_submitted_project = "fldis1ignLpvSF5LK"  # Name: form_submitted_project
            address_joined_no_name_from_form_submitted_project = "fld2iQEZHFPBS49n7"  # Name: address_joined_no_name (from form_submitted_project)
            user_consent = "fldWlAVD9AlG1NYak"  # Name: user_consent
            all_submitted_project_status = "fldFpKOTQTjnzpeZ3"  # Name: all_submitted_project_status
            all_user_unified_db_from_form_submitted_project = "fldJ3gNj9mFdrkZnM"  # Name: all_user_unified_db (from form_submitted_project)
            address_joined_from_ysws_project = "fldubS1WoqZqkxBh9"  # Name: address_joined (from ysws project)
            slack_id = "fldTrCGiaOMAVED5o"  # Name: slack_id
            order = "fld9YhS7dp9fWVzoo"  # Name: order
            code_url = "fldBDPByuRJgVWyjw"  # Name: code_url
            playable_url = "fldnRGAfDwBt9W94m"  # Name: playable_url


# fmt: on