# -*- coding: utf-8 -*-
# Generated by scripts/generate_airtable_ids.py. DO NOT EDIT MANUALLY.
# fmt: off

class AirtableIDs:
    """Container for generated Airtable Base, Table, and Field IDs."""

    class analytics_hack_clubbers:
        """IDs for Base 'analytics_hack_clubbers' (ID: appCGB6LccMzwkJZg)"""
        BASE_ID = "appCGB6LccMzwkJZg"

        class hack_clubbers:
            """IDs for Table 'hack_clubbers' (ID: tbluKHJi8hmg34uOF)"""
            TABLE_ID = "tbluKHJi8hmg34uOF"

            email = "fldPdy8PS8thWiO9e"  # Name: Email
            last_engagement_at = "fldR8L8CYXHOFqeXY"  # Name: Last Engagement At
            first_engagement_at = "flda4pqoaBcXthgVC"  # Name: First Engagement At
            first_engagement = "fldL2V98044JP2490"  # Name: First Engagement
            first_program = "fld0hbEmhMnlWTXxD"  # Name: First Program
            second_program = "fldPd7TRGEn4GNMIr"  # Name: Second Program
            first_name = "fldkCpESmYzhzszgD"  # Name: First Name
            last_name = "fldAkYYr1KPlT8Shg"  # Name: Last Name
            git_hub_username = "fldo3ijhoImccYWF1"  # Name: GitHub Username
            address_line_1 = "fldxz5WmFmTRAA8Uh"  # Name: Address Line 1
            address_line_2 = "fldQBRXGkwiTjE5Gk"  # Name: Address Line 2
            city = "fldYLQ9OQrKrpPreo"  # Name: City
            state = "fldLGhFMu4MNB7tbf"  # Name: State
            zip = "fldngtbpJA6Ki1XhT"  # Name: ZIP
            country = "fldqqoqqaX8Np6wec"  # Name: Country
            address_last_updated_at = "fldpgpL2L8avgJaSe"  # Name: Address Last Updated At
            programs = "fld6SNyJDuuaoDi02"  # Name: Programs
            last_engagement = "fldPsX86QczIT72xk"  # Name: Last Engagement
            total_engagements = "fldWYqRUOghaQ3AeG"  # Name: Total Engagements
            engagements_overview = "fldVPcRzBgat57RII"  # Name: Engagements Overview
            ship_count = "fldXDOr6f8UpEq2DF"  # Name: #ship count
            last_ship = "fldZ3wDpW7kRb1wtM"  # Name: Last #ship
            scrapbook_count = "fldMioUornccdgITA"  # Name: #scrapbook count
            last_scrapbook = "fldt1HbbtAPeHK5rh"  # Name: Last #scrapbook
            last_ysws_approved_at = "fldPCTdWTYBv95NXp"  # Name: Last YSWS Approved At
            last_ysws_approved = "fldaLkyCbE77obm45"  # Name: Last YSWS Approved
            ysws_approved_count = "fldckIW9hNmzW49Xk"  # Name: YSWS Approved Count
            ysws_weighted_grant_contribution = "fld7QYT7jIjUfWfwN"  # Name: YSWS Weighted Grant Contribution
            ysws_2025_weighted_grant_contribution = "fldMhjnyHcj95xAs9"  # Name: YSWS 2025 Weighted Grant Contribution
            ysws_weighted_grant_last_updated_at = "fldtasV6W8rMJ3Kxd"  # Name: YSWS Weighted Grant # Last Updated At
            ysws_first_stated_referral_reason = "fldw4NFCsgiFD2SZI"  # Name: YSWS First Stated Referral Reason
            ysws_first_stated_referral_category = "fldAkhtAHaM4nyuTJ"  # Name: YSWS First Stated Referral Category
            last_shipment_at = "fld9rYry1A4y5639q"  # Name: Last Shipment At
            last_shipment_contents = "fld6zA426vjcPgF6R"  # Name: Last Shipment Contents
            birthday = "fldT43iLDNGVLMbaG"  # Name: Birthday
            current_age = "fldVmL8HMrXuV5pZa"  # Name: Current Age
            search_field = "fldtFEnuqg8R3gwQy"  # Name: Search Field
            gender = "fldVuy6Bc3Ww1j9fH"  # Name: Gender
            slack_id = "fldV55ApIRoRXEWne"  # Name: Slack ID
            longitude = "fldl9sWFfdCAVeItF"  # Name: Longitude
            latitude = "fld6JDgRLSPq8Lp2v"  # Name: Latitude
            geocoded_country = "fldkoQz2PXvI02kOD"  # Name: Geocoded Country
            phone_number = "fldlLCvLTuQCKHUNd"  # Name: Phone Number
            create_shipment = "fldrjbBU9ki5rf3DH"  # Name: create shipment!

        class field_mapping_rules:
            """IDs for Table 'field_mapping_rules' (ID: tbl7SkwqGYtFl4pe4)"""
            TABLE_ID = "tbl7SkwqGYtFl4pe4"

            loops_so_field_to_map = "fldnjsCqhetjq4wBh"  # Name: Loops.so Field To Map
            hack_clubber_field = "fldd3p4ZDWIjjkdKt"  # Name: Hack Clubber Field

        class program_mapping_rules:
            """IDs for Table 'program_mapping_rules' (ID: tbl02flnwdqn8NcgG)"""
            TABLE_ID = "tbl02flnwdqn8NcgG"

            loops_so_field_to_map = "fldgtnrn7tq1dNjDT"  # Name: Loops.so Field To Map
            program = "fld6xM9D8pPFankEB"  # Name: Program


# fmt: on