# -*- coding: utf-8 -*-
# Generated by scripts/generate_airtable_ids.py. DO NOT EDIT MANUALLY.
# fmt: off

class AirtableIDs:
    """Container for generated Airtable Base, Table, and Field IDs."""

    class analytics_hack_clubbers:
        """IDs for Base 'analytics_hack_clubbers' (ID: appCGB6LccMzwkJZg)"""
        BASE_ID = "appCGB6LccMzwkJZg"

        class hack_clubbers:
            """IDs for Table 'hack_clubbers' (ID: tbluKHJi8hmg34uOF)"""
            TABLE_ID = "tbluKHJi8hmg34uOF"

            email = "fldPdy8PS8thWiO9e"  # Name: Email
            last_engagement_at = "fldR8L8CYXHOFqeXY"  # Name: Last Engagement At
            first_engagement_at = "flda4pqoaBcXthgVC"  # Name: First Engagement At
            first_engagement = "fldL2V98044JP2490"  # Name: First Engagement
            first_program = "fld0hbEmhMnlWTXxD"  # Name: First Program
            second_program = "fldPd7TRGEn4GNMIr"  # Name: Second Program
            first_name = "fldkCpESmYzhzszgD"  # Name: First Name
            last_name = "fldAkYYr1KPlT8Shg"  # Name: Last Name
            git_hub_username = "fldo3ijhoImccYWF1"  # Name: GitHub Username
            address_line_1 = "fldxz5WmFmTRAA8Uh"  # Name: Address Line 1
            address_line_2 = "fldQBRXGkwiTjE5Gk"  # Name: Address Line 2
            city = "fldYLQ9OQrKrpPreo"  # Name: City
            state = "fldLGhFMu4MNB7tbf"  # Name: State
            zip = "fldngtbpJA6Ki1XhT"  # Name: ZIP
            country = "fldqqoqqaX8Np6wec"  # Name: Country
            address_last_updated_at = "fldpgpL2L8avgJaSe"  # Name: Address Last Updated At
            programs = "fld6SNyJDuuaoDi02"  # Name: Programs
            last_engagement = "fldPsX86QczIT72xk"  # Name: Last Engagement
            total_engagements = "fldWYqRUOghaQ3AeG"  # Name: Total Engagements
            engagements_overview = "fldVPcRzBgat57RII"  # Name: Engagements Overview
            ship_count = "fldXDOr6f8UpEq2DF"  # Name: #ship count
            last_ship = "fldZ3wDpW7kRb1wtM"  # Name: Last #ship
            scrapbook_count = "fldMioUornccdgITA"  # Name: #scrapbook count
            last_scrapbook = "fldt1HbbtAPeHK5rh"  # Name: Last #scrapbook
            last_ysws_approved_at = "fldPCTdWTYBv95NXp"  # Name: Last YSWS Approved At
            last_ysws_approved = "fldaLkyCbE77obm45"  # Name: Last YSWS Approved
            ysws_approved_count = "fldckIW9hNmzW49Xk"  # Name: YSWS Approved Count
            ysws_weighted_grant_contribution = "fld7QYT7jIjUfWfwN"  # Name: YSWS Weighted Grant Contribution
            ysws_2025_weighted_grant_contribution = "fldMhjnyHcj95xAs9"  # Name: YSWS 2025 Weighted Grant Contribution
            ysws_weighted_grant_last_updated_at = "fldtasV6W8rMJ3Kxd"  # Name: YSWS Weighted Grant # Last Updated At
            ysws_first_stated_referral_reason = "fldw4NFCsgiFD2SZI"  # Name: YSWS First Stated Referral Reason
            ysws_first_stated_referral_category = "fldAkhtAHaM4nyuTJ"  # Name: YSWS First Stated Referral Category
            last_shipment_at = "fld9rYry1A4y5639q"  # Name: Last Shipment At
            last_shipment_contents = "fld6zA426vjcPgF6R"  # Name: Last Shipment Contents
            birthday = "fldT43iLDNGVLMbaG"  # Name: Birthday
            current_age = "fldVmL8HMrXuV5pZa"  # Name: Current Age
            search_field = "fldtFEnuqg8R3gwQy"  # Name: Search Field
            gender = "fldVuy6Bc3Ww1j9fH"  # Name: Gender
            slack_id = "fldV55ApIRoRXEWne"  # Name: Slack ID
            longitude = "fldl9sWFfdCAVeItF"  # Name: Longitude
            latitude = "fld6JDgRLSPq8Lp2v"  # Name: Latitude
            geocoded_country = "fldkoQz2PXvI02kOD"  # Name: Geocoded Country
            phone_number = "fldlLCvLTuQCKHUNd"  # Name: Phone Number
            create_shipment = "fldrjbBU9ki5rf3DH"  # Name: create shipment!

        class field_mapping_rules:
            """IDs for Table 'field_mapping_rules' (ID: tbl7SkwqGYtFl4pe4)"""
            TABLE_ID = "tbl7SkwqGYtFl4pe4"

            loops_so_field_to_map = "fldnjsCqhetjq4wBh"  # Name: Loops.so Field To Map
            hack_clubber_field = "fldd3p4ZDWIjjkdKt"  # Name: Hack Clubber Field

        class program_mapping_rules:
            """IDs for Table 'program_mapping_rules' (ID: tbl02flnwdqn8NcgG)"""
            TABLE_ID = "tbl02flnwdqn8NcgG"

            loops_so_field_to_map = "fldgtnrn7tq1dNjDT"  # Name: Loops.so Field To Map
            program = "fld6xM9D8pPFankEB"  # Name: Program

        class programs:
            """IDs for Table 'programs' (ID: tblo0e0B4UQ4edi31)"""
            TABLE_ID = "tblo0e0B4UQ4edi31"

            name = "fldYqdE55u9NgTpTd"  # Name: Name
            hcers_brought_in_who_did_a_ysws_this_month = "fldEvQDo61AbZ30wa"  # Name: HCers brought in who did a YSWS this month
            hcers_brought_in_who_did_a_ysws_this_year = "fldNp5rctO7BBiLQq"  # Name: HCers brought in who did a YSWS this year
            hcers_brought_in_this_month = "fldmjKOYaauHTf25p"  # Name: HCers brought in this month
            hcers_brought_in_this_year = "fldbhLElo2h9l0Dnl"  # Name: HCers brought in this year
            hcers_brought_in_this_year_who_have_engaged_in_a_2nd_program = "fldg5PKX47u5c3ErV"  # Name: HCers brought in this year who have engaged in a 2nd program
            mapping_rules = "fldAWCJQoAQ6e4z2x"  # Name: Mapping Rules
            participating_hack_clubbers = "fldofIaFiFbHYGpW8"  # Name: Participating Hack Clubbers
            hack_clubbers_brought_in_by_program = "fldiG1J2xgqa8lSLL"  # Name: Hack Clubbers Brought In By Program
            hack_clubbers_with_this_program_as_their_2nd_engagement = "fld8bY4axzv7hmwDA"  # Name: Hack Clubbers With This Program As Their 2nd Engagement


    class neighborhood:
        """IDs for Base 'neighborhood' (ID: appnsN4MzbnfMY0ai)"""
        BASE_ID = "appnsN4MzbnfMY0ai"

        class neighbors:
            """IDs for Table 'neighbors' (ID: tblTGpK7QgwsqT8t0)"""
            TABLE_ID = "tblTGpK7QgwsqT8t0"

            email = "flduN2BlNtozsp5xZ"  # Name: email
            is_irl = "fldIvA3RbNiyzm6vm"  # Name: isIRL
            total_time_hackatime_hours = "fldgawsm3YG4b2C5V"  # Name: totalTimeHackatimeHours
            total_time_stopwatch_hours = "fldD8IywF8keOhSJd"  # Name: totalTimeStopwatchHours
            total_time_combined_hours = "fldQmyJBIHfmAp73d"  # Name: totalTimeCombinedHours
            full_name = "fldF7r89RpZ0WsaW4"  # Name: Full Name
            date_of_birth = "fldOygvFVgwArnj36"  # Name: Date of Birth
            token = "fldTMjrUrqTflOGBx"  # Name: token
            sessions = "fld1HC2XIHKk29AQe"  # Name: sessions
            github_username = "fldjw0OdVL7EN9521"  # Name: githubUsername
            commits = "fldiV80pumQcuswPo"  # Name: commits
            invites = "flduLNKHWAqsMCQ5Y"  # Name: invites
            slack_neighbor = "fld3fOnOAo22kPq3c"  # Name: slackNeighbor
            pfp_from_slack_neighbor = "fldv0qc5jSXftaxxt"  # Name: Pfp (from slackNeighbor)
            pfp = "fldZNlIzs5FFERF1g"  # Name: Pfp
            slack_id_from_slack_neighbor = "fldtGzNkSmENJ4dZM"  # Name: Slack ID (from slackNeighbor)
            slack_handle_from_slack_neighbor = "fldS8nY4J5k6RqJOG"  # Name: Slack Handle (from slackNeighbor)
            full_name_from_slack_neighbor = "fldh3GA2DutgIRvZ4"  # Name: Full Name (from slackNeighbor)
            created_at = "fldHX2x94MK0eCZz5"  # Name: createdAt
            has_hackatime_at = "fldBB56XVkvKAzFN8"  # Name: hasHackatimeAt
            github_project = "fldKPKw7ZtnshB7Qo"  # Name: githubProject
            project_description = "fldzCQ2BmS7kkOpa9"  # Name: projectDescription
            project_name = "fldjBwy9h7Aixt40D"  # Name: projectName
            hackatime_projects = "fldwulpnDLhKQP8Qi"  # Name: hackatimeProjects
            loops_special_set_full_name = "fldtoOwj09ywVl6of"  # Name: Loops - Special - setFullName
            loops_neighborhood_sign_up_at = "fldud54x3An7UBqXW"  # Name: Loops - neighborhoodSignUpAt
            loops_birthday = "fldulwgHvMeu4kIFQ"  # Name: Loops - birthday
            loops_neighborhood_has_hackatime_at = "fldMNOI6mgpffAEyW"  # Name: Loops - neighborhoodHasHackatimeAt
            zapier_added_to_neighborhood_mailing_list_at = "fldOvjuA3x1UF3clq"  # Name: Zapier - Added to Neighborhood mailing list at
            apps = "fldgP54dgV9BYOOUD"  # Name: Apps
            devlog = "fldijYi51GpUlaOJk"  # Name: devlog
            total_checked_time = "fldEy1busms5l0z16"  # Name: totalCheckedTime
            total_time_hackatime_seconds = "fldoWMncGnNk7PkZe"  # Name: totalTimeHackatimeSeconds
            total_time_stopwatch_minutes = "fldIXiD6QzBKg0q4V"  # Name: totalTimeStopwatchMinutes
            hack_clubber = "fldzsY67bxOBzpF2U"  # Name: Hack Clubber
            gender_from_hack_clubber = "fldYuNPOiE9BZTDWB"  # Name: Gender (from Hack Clubber)
            first_engagement_from_hack_clubber = "fldmHCJ4LEFrCUgLr"  # Name: First Engagement (from Hack Clubber)
            first_engagement_at_from_hack_clubber = "fldOeJoYxsqUVrags"  # Name: First Engagement At (from Hack Clubber)
            email_from_hack_clubber = "fldynlPE3lSYTNoPn"  # Name: Email (from Hack Clubber)
            ysws_project_submission_from_apps = "fldCCqeLZ98QGjuNz"  # Name: YSWS Project Submission (from Apps)
            move_in_date = "fldvl9C0PdGB4rCSJ"  # Name: move-in-date
            move_out_date = "flddD3Uq93uS3SoT4"  # Name: move-out-date
            rooms = "fld1CRYR8fm1gWfeI"  # Name: Rooms
            room_gender = "fldmqxYDLp98zdpMC"  # Name: RoomGender
            comments = "fldtiQ5qz93Pg2eHU"  # Name: Comments
            total_days = "fldSO66JuHbuhkQKr"  # Name: total-days
            visa_home_assignments = "fldmTtg5U8BmPQXlO"  # Name: VisaHomeAssignments
            age_at_sign_up = "fldzuo4LvG4l1ayDr"  # Name: Age At Sign-Up
            age = "fldwNxCpsI3Tg9fON"  # Name: Age
            age_eligible_at = "fld6k4njoQS3nmo1o"  # Name: ageEligibleAt
            time_over1_hour = "fldvcDJtToZy3MmiE"  # Name: timeOver1Hour
            time_over25_hours = "fldAjUL5ho3DvMqhg"  # Name: timeOver25Hours
            time_over50_hours = "fldBB0vqfHjHFwyyB"  # Name: timeOver50Hours
            time_over75_hours = "fldqHEpIypRvxH3bL"  # Name: timeOver75Hours
            time_over100_hours = "fldNmKOC1UmhuUCmu"  # Name: timeOver100Hours
            ysws_project_submitted_at = "fldjgX1MI2N6JwULl"  # Name: yswsProjectSubmittedAt
            granted_hours = "fldpbGt3d43j9nUYW"  # Name: GrantedHours
            ysws_project_submitted_staff_approved = "fldoBkA3lrmvtFoyX"  # Name: yswsProjectSubmittedStaffApproved
            country = "fldodb9BuLa4ApYbN"  # Name: country
            airport = "fldzzTahGopPmDTkl"  # Name: airport
            has_visa = "fldAuoDvTz3IH4i3h"  # Name: hasVisa
            unreviewed_devlog_count = "fldFEHEfibio3eiQ1"  # Name: unreviewedDevlogCount
            ysws_project_submission = "fldWLN24iL2P4awTX"  # Name: YSWS Project Submission
            ysws_project_submission_copy = "fld64FAjNTpT18NHi"  # Name: YSWS Project Submission copy
            ysws_project_submission_copy = "fldncW9I2k7DEelDT"  # Name: YSWS Project Submission copy
            hacktendo_signup = "fldUS4pHu4yOBFRXJ"  # Name: hacktendoSignup
            stay = "fldznNSh0XWhjFPbq"  # Name: stay
            start_date_from_stay = "fldWYQ1b2RXGMQ3lD"  # Name: start_date (from stay)
            end_date_from_stay = "fldb16euh5J5njAmR"  # Name: end_date (from stay)
            wants_flight_stipend = "fldKwfaokHy4iRc01"  # Name: WantsFlightStipend
            hackatime_review_url_from_ysws_project_submission = "fldhrrkn3y92EI0em"  # Name: hackatimeReviewUrl (from YSWS Project Submission)
            approved_flight_stipend = "fld97NM9KyuWjn2gH"  # Name: approvedFlightStipend
            sent_flight_stipend_from_wants_flight_stipend = "fldr7skoqF7FQIM5C"  # Name: sentFlightStipend (from wantsFlightStipend)
            been_dmed = "fldaSxJCk8AcCYv3y"  # Name: beenDMed
            slack_handle_from_slack_neighbor_2 = "fldM6S1Sui1EVQwMz"  # Name: Slack Handle (from slackNeighbor) 2
            wants_flight_stipend_2 = "fldJGS9E04wvgEtOy"  # Name: wantsFlightStipend 2
            wants_flight_stipend_3 = "fldbfpdS5cTTkCVnt"  # Name: wantsFlightStipend 3
            hard_review = "fldAVEU1YuuuJDa9l"  # Name: hardReview
            gavefeedback = "fldcHX7aY7gyzZFaL"  # Name: gavefeedback
            playable_url_from_ysws_project_submission_copy = "fldazeuFpftkgJDbi"  # Name: Playable URL (from YSWS Project Submission copy)
            cosmin_vibe = "fldHkpyvzOZPQwHRp"  # Name: cosminVibe
            github_link_from_ysws_project_submission_copy = "fldJbCJLNmaDglY8N"  # Name: Github Link (from YSWS Project Submission copy)
            reviews_given = "fldGstrAsQnJyrn4I"  # Name: reviewsGiven
            reviews_received = "fldIPHBwelYI2LYF5"  # Name: reviewsReceived
            star_avg = "fld9VkjiJxZM1mApV"  # Name: starAvg
            stipends_given = "fldgCIsH5iN84mLFL"  # Name: StipendsGiven
            house = "fld86rf2ndKvPWOQG"  # Name: House
            hide_jake_the_dog = "fldqGNqdQghBymbUB"  # Name: hideJakeTheDog
            waiver = "fldtgrZArDX7CwTwD"  # Name: waiver
            waivers = "fldXE3HFiSsc3f8pF"  # Name: Waivers
            is_doing_freedom_week = "fld2yaxWWeEsAggcE"  # Name: isDoingFreedomWeek
            optional_override_hours_spent_from_ysws_project_submission = "fld3LN9aJskuLjc0b"  # Name: Optional - Override Hours Spent (from YSWS Project Submission)
            weighted_grants_contribution = "fldzVqjJSTHkYnr81"  # Name: weightedGrantsContribution
            weighted_grants_contribution_copy = "fldzCqpWnlG8vMnEi"  # Name: weightedGrantsContribution copy
            ysws_project_submission_copy = "fldLNpQEwcAng92pX"  # Name: YSWS Project Submission copy
            booking_status_from_stay = "fldK7mp9Qssv0gKRJ"  # Name: bookingStatus (from stay)
            house_from_stay = "fld8vlhKtf1hKZ7lc"  # Name: house (from stay)
            flight_booked_home = "fld2kOfzZQoXKCriQ"  # Name: flightBookedHome
            independence_program = "fldKWXw69FjXzuz7a"  # Name: independenceProgram
            money_spent = "fldUfFXEzJOPOcG3I"  # Name: moneySpent
            request_to_continue = "fld3efwjS511mj19c"  # Name: requestToContinue
            in_person_status = "fld9T9OuZ0Fn8KRoq"  # Name: In-personStatus
            what_staff_member_signed_off_on_your_situation_from_in_person_status = "fldBa36r0pGRF7668"  # Name: What staff member signed off on your situation? (from In-personStatus)
            what_s_your_exact_situation_regarding_your_return_home_from_in_person_status = "fldZoPjOzIttkUA57"  # Name: What's your exact situation regarding your return home? (from In-personStatus)
            screenshot_of_flight_confirmation_mobile_screenshot_ok_from_in_person_status = "fld7s2PdQeifUXD3v"  # Name: Screenshot of flight confirmation (mobile screenshot ok) (from In-personStatus)
            what_is_the_current_date_you_re_returning_from_sfo_to_your_home_country_leave_empty_if_you_do_not_have_a_return_flight_from_in_person_status = "fldtukpCb8PQWdmXu"  # Name: What is the current date you're returning from SFO to your home country? (leave empty if you do not have a return flight) (from In-personStatus)
            has_flight_from_stay = "fld6rT9bK1mGi7OgI"  # Name: hasFlight (from stay)
            staff_verified = "fldLbINAvbSGRiWm7"  # Name: staff verified
            staff_notes = "fldwKZn2Zo4u82T25"  # Name: staff notes
            staying_in_sf_post_neighborhood = "fldkmemhgecSB4j4j"  # Name: Staying in SF post neighborhood
            what_is_the_current_date_you_re_returning_from_sfo_to_your_home_country_leave_empty_if_you_do_not_have_a_return_flight_from_in_person_status_2 = "fldrgPO6IYG8wcmZ1"  # Name: What is the current date you're returning from SFO to your home country? (leave empty if you do not have a return flight) (from In-personStatus) 2
            departure_status = "fldorShRImf3nbRRo"  # Name: Departure Status
            departure_parent_confirmation_email = "fldx5spFFEqH5XoIy"  # Name: Departure - Parent Confirmation Email
            departure_status = "fld1Ky1vP3TSaBvQP"  # Name: Departure - Status
            departure_flight_departure_date = "fldaErKFPpsKJezh9"  # Name: Departure - Flight Departure Date
            departure_owner = "fldFYakaI4hAN1D5l"  # Name: Departure - Owner
            departure_notes = "fldDFhDcuN125e0XQ"  # Name: Departure - Notes
            parent_email = "fld8bb4QTk7ZjUbP3"  # Name: Parent Email
            departure_flight_ticket = "fldlarEaz7pNHWihB"  # Name: Departure - Flight Ticket
            departure_automated_check = "fldrC0dVepUKl9Cd1"  # Name: Departure - Automated Check
            departure_done_zach_sign_off = "fldgAh7wayQvKwgyD"  # Name: Departure - Done, Zach Sign Off
            created_at_from_ysws_project_submission = "fldIqZtG7vbnZ7SpI"  # Name: Created At (from YSWS Project Submission)
            optional_override_hours_spent_from_ysws_project_submission_2 = "fld4zZEnyrcYl57db"  # Name: Optional - Override Hours Spent (from YSWS Project Submission) 2
            post_event_flight_stipend_reimbursement_requests = "fldcvYLWKIKjlJYc8"  # Name: Post Event - Flight Stipend Reimbursement Requests
            post_event_hour_transfers = "fldtReVjBNoJytnoS"  # Name: Post Event - Hour Transfers

        class hackatime_projects:
            """IDs for Table 'hackatime_projects' (ID: tblIqliBgKvoNT3uD)"""
            TABLE_ID = "tblIqliBgKvoNT3uD"

            id_auto = "fld5AIb2Hce93a7no"  # Name: idAuto
            name = "fldxfUM1hVmUp9wcG"  # Name: name
            email = "flddVY9cveGbXqP6K"  # Name: email
            commits = "fldCiY5HxO6yvVvWo"  # Name: commits
            description = "fld0s3MW3Q77mr53z"  # Name: description
            neighbor = "fldYgoiBlHUMElnYK"  # Name: neighbor
            github_link = "fldLTbhfMJVYPVjB7"  # Name: githubLink
            invites = "fld8TaHXV4Ev8cUm6"  # Name: invites
            created_at = "fldl0zGygN16MWynk"  # Name: createdAt
            sessions = "fld9d6sivClb6GIwa"  # Name: sessions
            apps = "fldSJ8ltjI8CMNUyy"  # Name: Apps
            name_from_apps = "fldAl407aK8q34z5r"  # Name: Name (from Apps)
            app_name = "fldp1T9BUcsh04p6j"  # Name: appName
            calcul = "fld1RndPLnMvmD7zf"  # Name: Calcul
            slack_id = "fldDu4An1KY5utXC1"  # Name: slackId
            total_time = "fldqSsiI9hZb2OW9g"  # Name: totalTime
            total_time_hours = "fldILpudcwm5io04z"  # Name: totalTimeHours
            more_than_one_user = "fldlPV7I6oORuOIj1"  # Name: moreThanOneUser
            created = "fld7SuT6aT0AUGGyC"  # Name: Created
            ysws_project_submission_from_apps = "fldYOwYZ57sL0r4DE"  # Name: YSWS Project Submission (from Apps)


    class shipwrecked:
        """IDs for Base 'shipwrecked' (ID: appcfQcNlm6vXUOad)"""
        BASE_ID = "appcfQcNlm6vXUOad"

        class rsvps:
            """IDs for Table 'rsvps' (ID: tblGW44enlxcYjDjS)"""
            TABLE_ID = "tblGW44enlxcYjDjS"

            email = "fldHtR3taM8g8CWXC"  # Name: Email
            checked_in = "fldawOqtBrNH0P65U"  # Name: Checked in?
            legal_first_name_from_invite = "fldw1qqyRYFHIf8CZ"  # Name: Legal First Name (from Invite)
            last_name_from_invite = "fldQWM079Q0ZNEGWj"  # Name: Last Name (from Invite)
            preferred_name_from_invite = "fldgaZ6RUA0HK5WWl"  # Name: Preferred Name (from Invite)
            slack_id_from_invite = "fldUbOb77RWYbuRR7"  # Name: Slack ID (from Invite)
            birthday = "fldbnLqZdBx5kHXIY"  # Name: Birthday
            current_age = "fld4F4Ku4wXE3PNFL"  # Name: Current Age
            pronouns_from_invite_link = "fldcuxidmKcpfl2Fk"  # Name: Pronouns (from Invite Link)
            total_hours_to_island = "fldRdGKymH2ZqdvI9"  # Name: totalHoursToIsland
            attending = "fldHjSf3Q6Hn6EADP"  # Name: Attending
            i_prefer_to_be_with_my_requested_roommate_than_in_the_executive_suite_from_roommate_form_link = "fldn6RqTDKR6xRLLP"  # Name: I prefer to be with my requested roommate than in the executive suite. (from Roommate Form Link)
            slack_ids_of_your_requested_roommates_from_roommate_form_link = "fldmZ5WqbPe6QTnpx"  # Name: Slack IDs of your requested roommates (from Roommate Form Link)
            how_many_roommates_would_you_like_to_have_from_roommate_form_link = "fldQMpqxRR9qjUYd0"  # Name: How many roommates would you like to have? (from Roommate Form Link)
            what_are_some_interests_you_have_from_roommate_form_link = "fldGO2fp1I8pZEdzg"  # Name: What are some interests you have? (from Roommate Form Link)
            do_you_like_having_background_noise_music_in_your_room_from_roommate_form_link = "fldmnXN3f9fKsOgFg"  # Name: Do you like having background noise/music in your room? (from Roommate Form Link)
            how_tidy_are_you_from_roommate_form_link = "fldjqwY6eky75PgOj"  # Name: How tidy are you? (from Roommate Form Link)
            what_gender_would_you_like_to_be_paired_with_from_roommate_form_link = "fld4ISEEqOa1trjcd"  # Name: What gender would you like to be paired with? (from Roommate Form Link)
            what_gender_do_you_identify_as_from_roommate_form_link = "fld0YwptqQFtWmM4y"  # Name: What gender do you identify as? (from Roommate Form Link)
            building = "fldH5ETcRl4JhqhsE"  # Name: Building
            room_number = "fldW9OXr5dUKLqngd"  # Name: Room Number
            viral = "fld7jUN8anhT5Uiic"  # Name: Viral
            first_name = "fldZx3qAINejnw3iU"  # Name: First Name
            last_name = "fldbrTWeaFL8qwwUK"  # Name: Last Name
            loops_first_name = "fldK8GsyirxyStpWH"  # Name: Loops - firstName
            loops_last_name = "fldIeNq9sxBpeSsjz"  # Name: Loops - lastName
            loops_birthday = "fldg2PDzyVgntfhdt"  # Name: Loops - birthday
            loops_shipwrecked_sign_up_at = "fldpFp794BweHvxWN"  # Name: Loops - shipwreckedSignUpAt
            zapier_added_to_shipwrecked_loops_mailing_list_at = "fldtjf0WgIPkxARkk"  # Name: Zapier - Added to Shipwrecked Loops mailing list at
            referral_code = "fld5DXnUQLxcjn2Xk"  # Name: referral_code
            referral_type = "fldOlvpXGZfaKQEN7"  # Name: referral_type
            loops_shipwrecked_sign_up_position = "fld2qb4DViP6e9N4b"  # Name: Loops - shipwreckedSignUpPosition
            ip_address = "fldFAELbzAbzqxjK8"  # Name: IP Address
            country = "fldS7C8f2BqUmL1Fw"  # Name: Country
            participants_referred = "fld1KMBVLjJtxMtmZ"  # Name: Participants Referred
            number_of_referrals = "fldV0f6k0kjNhdDQJ"  # Name: Number of Referrals
            disqualified_from_raffle = "fld9MCo0sAfuEXYii"  # Name: Disqualified_from_raffle
            non_disqualified_referrals = "fldHKZkydQU1p0tjO"  # Name: Non-Disqualified Referrals
            number_of_referrals_18 = "fldSux7TS7q9ZxLEK"  # Name: Number of Referrals <=18
            add_to_slack = "fldtTt0CoXuqWdiSU"  # Name: AddToSlack?
            hack_clubber = "fldCPXnlvgkO8QEPc"  # Name: Hack Clubber
            hack_clubber_first_engagement = "fldYeV8CZYpqEEiw2"  # Name: Hack Clubber – First Engagement
            hack_clubber_ysws = "fldBfLG18FaRMtIbX"  # Name: Hack Clubber – YSWS
            rsvps_last_24h = "fldDhIqWDBfRFVTvs"  # Name: rsvps_last_24h
            created_at = "fldgz5xzYbF7TORKE"  # Name: Created At
            created_at = "fldxZBl3Y92B7icVV"  # Name: createdAt
            age_eligible_at = "fld8tatAv1Syhf8Kp"  # Name: ageEligibleAt
            has_hackatime_at = "fldO4HAkyTTRiraKG"  # Name: hasHackatimeAt
            logged_first_hour = "fldOZcXpk5ZUtocmZ"  # Name: loggedFirstHour
            logged_ten_hours = "fldEUzm2kzocxUA8S"  # Name: loggedTenHours
            submitted_first_project = "fld3Mu3BoCktJIdcw"  # Name: submittedFirstProject
            first_project_approved = "fldSWTtuYyq7jnRTq"  # Name: firstProjectApproved
            logged_first_hour_on_second_project = "fldj7etQaidqXuc6K"  # Name: loggedFirstHourOnSecondProject
            submitted_second_project = "fldbw0lZyl92GxlBh"  # Name: submittedSecondProject
            second_project_approved = "fldoGN2NW6jMhh0Nv"  # Name: secondProjectApproved
            logged_first_hour_on_third_project = "fldfIN0aJJ6H75GCs"  # Name: loggedFirstHourOnThirdProject
            submitted_third_project = "fldeLt3MnwE2lm6UY"  # Name: submittedThirdProject
            third_project_approved = "fld7CXYUG2yDdvZ7t"  # Name: thirdProjectApproved
            logged_first_hour_on_fourth_project = "fldAqWBiXsIvCh3Vt"  # Name: loggedFirstHourOnFourthProject
            submitted_fourth_project = "fldkJCAM5lHwt5xyK"  # Name: submittedFourthProject
            fourth_project_approved = "fldQnuIrqn0Dy17Jd"  # Name: fourthProjectApproved
            user_exists_in_bay = "fldm1Ns9lKIaJNvnE"  # Name: userExistsInBay
            total_raw_hackatime_hours = "fld1tdBSSLKnKOo0D"  # Name: totalRawHackatimeHours
            total_approved_hackatime_hours = "fldJ1OC5ibU6vJe8t"  # Name: totalApprovedHackatimeHours
            hours_to_island_viral = "fldN3iNiCnfvRbX0h"  # Name: hoursToIslandViral
            hours_to_island_shipped = "fld5gJK1LhjnyFD8w"  # Name: hoursToIslandShipped
            hours_to_island_unapproved = "fld4biaWuudNGMQ36"  # Name: hoursToIslandUnapproved
            shell_hours = "fldqudjHM1ogatTQK"  # Name: shellHours
            loops_shipwrecked_user_exists_in_bay = "fldvXPNRWtyLALtIo"  # Name: Loops - shipwreckedUserExistsInBay
            created = "fldePoj75HS2SGHQb"  # Name: Created
            slack_id = "fldUlitvx7GDIhAxx"  # Name: slackId
            fetch_slack_id = "fldjxVuEeKbSxiKIT"  # Name: Fetch slackID
            user_attempted_identity = "fldoQWEvuaHkabMJS"  # Name: userAttemptedIdentity
            night_before_accommodations = "fldQXz5G0HhWL8eHs"  # Name: Night Before Accommodations
            night_after_accommodations = "fldVZnsxfDf2khC18"  # Name: Night After Accommodations
            invite_link = "fldKQXmuANywRragv"  # Name: Invite Link
            waitlist_from_invite_link = "fld9paKaakz75hD8j"  # Name: Waitlist (from Invite Link)
            t_shirt_size_from_invite_link = "fldv0h6MzUGfPmlNG"  # Name: T-Shirt Size (from Invite Link)
            needs_night_after_accommodations_from_invite_link = "fld8S9KyZjXjAEsFj"  # Name: Needs Night After Accommodations (from Invite Link)
            needs_night_before_accommodations_from_invite_link = "flduy9M55adVDvHQz"  # Name: Needs Night Before Accommodations (from Invite Link)
            international_from_invite_link = "fldcRWqdILiyjIl0t"  # Name: International (from Invite Link)
            applying_for_merit_based_stipend_from_invite_link = "flduDzbEBvFizGah5"  # Name: Applying for Merit-Based Stipend (from Invite Link)
            estimated_flight_stipend_from_invite_link = "fldX1jBj82erZFzU0"  # Name: Estimated Flight Stipend (from Invite Link)
            estimated_flight_cost_from_invite_link = "fldPWUDHigNA15hgp"  # Name: Estimated Flight Cost (from Invite Link)
            nearest_airport_code_s_from_invite_link = "fldDf3g0tw1Sndws6"  # Name: Nearest Airport Code(s) (from Invite Link)
            flying_in_from_invite_link = "fldH3OibM55eFXnDb"  # Name: Flying In (from Invite Link)
            parent_phone_number_from_invite_link = "fldLP8gNhuBy1rHNB"  # Name: Parent Phone Number (from Invite Link)
            parent_email_from_invite_link = "fldmb1hFRFaT1QfDU"  # Name: Parent Email (from Invite Link)
            parent_last_name_from_invite_link = "fldkz6tAZ8OVbGkdM"  # Name: Parent Last Name (from Invite Link)
            parent_first_name_from_invite_link = "fldkicDndSp5wOHyV"  # Name: Parent First Name (from Invite Link)
            address_from_invite_link = "fldTQZ5lpUL2rnr66"  # Name: Address (from Invite Link)
            phone_number_from_invite_link = "fldYJoOWmLZgCxdyZ"  # Name: Phone Number (from Invite Link)
            preferred_name_from_invite_link = "fldNu3oqylQbejPUv"  # Name: Preferred Name (from Invite Link)
            flight_link = "fldUYY0rfWz6djZBY"  # Name: Flight Link
            inbound_flight_number_from_flight = "fldls1Vu7FdiNytMF"  # Name: Inbound Flight Number (from Flight)
            inbound_flight_time_from_flights = "fld1Jeue8UyTRuqFc"  # Name: Inbound Flight Time (from Flights)
            outbound_flight_number_from_flight = "fldsb1X5xwbBQXLr0"  # Name: Outbound Flight Number (from Flight)
            outbound_flight_time_from_flight = "fldt92dh2zHqUxLfN"  # Name: Outbound Flight Time (from Flight)
            hcb_email_from_flight = "fldjqB1ckBzAbY0Q3"  # Name: HCB Email (from Flight)
            temp_2_hit_viral_wave = "fldZglg7aXOII3eng"  # Name: (Temp 2) - Hit viral wave
            spot_reservation_link = "fldaHT9x9qSkpnAm1"  # Name: Spot Reservation Link
            need_based_stipend_application_link = "fldOFLcLMFAoHkoLw"  # Name: Need-Based Stipend Application Link
            what_s_something_only_you_can_bring_to_shipwrecked_from_need_based_stipend_application_link = "fldKncXwBUhZw66NT"  # Name: What's something only you can bring to Shipwrecked? (from Need-Based Stipend Application Link)
            what_are_you_currently_obsessed_with_that_has_nothing_to_do_with_hack_club_from_need_based_stipend_application_link = "fldkXPSD0PAq3mWu0"  # Name: What are you currently obsessed with, that has nothing to do with Hack Club? (from Need-Based Stipend Application Link)
            demo_link_from_need_based_stipend_application_link = "fldjyhbDxOzoSsB9O"  # Name: Demo Link (from Need-Based Stipend Application Link)
            repo_link_from_need_based_stipend_application_link = "fld3XW3YUCRPzLm2x"  # Name: Repo Link (from Need-Based Stipend Application Link)
            description_of_project_from_need_based_stipend_application_link = "fldgrl1tzSmzKaU68"  # Name: Description of Project (from Need-Based Stipend Application Link)
            amount_able_to_contribute_from_need_based_stipend_application_link = "fldFb0V9XzbsY1ESh"  # Name: Amount Able to Contribute (from Need-Based Stipend Application Link)
            cheapest_round_trip_from_need_based_stipend_application_link = "fld2bzcyXuIdXaAu2"  # Name: Cheapest Round Trip (from Need-Based Stipend Application Link)
            departing_airport_from_need_based_stipend_application_link = "fldtvfFFIGNaALkqw"  # Name: Departing Airport (from Need-Based Stipend Application Link)
            need_based_stipend_amount = "fld4DLwwlm006KSwr"  # Name: Need-Based Stipend Amount
            requested_reimbursement_from_flight = "fld77YzWZnEKkukmM"  # Name: Requested Reimbursement (from Flight)
            unaccompanied_minor_from_flight_link = "fldWx0IWw6VbmRSZk"  # Name: Unaccompanied Minor (from Flight Link)
            spot_reservation_approved = "fld97KMRsRYNuRyXw"  # Name: Spot Reservation Approved
            trigger_nudge_email = "fldQ9HVZm3pqvxaCm"  # Name: trigger_nudge_email
            flights_slack_id = "fldPqABnaNnj6JA4b"  # Name: Flights Slack ID
            spot_reservation_slack_id = "fldeZ91SJFYhtoAnL"  # Name: Spot Reservation Slack ID
            purchased_hours = "fld1qbULdU2A5OZAD"  # Name: purchasedHours
            purchased_hours_not_percent = "fldxezj4zSybad3ru"  # Name: Purchased Hours (not percent)
            public_flights_from_flight = "fldvOk0koArVFbzIq"  # Name: Public Flights (from Flight)
            not_attending = "fldwErRiOx5KbNLfZ"  # Name: Not Attending
            reimbursement_transaction_link = "fldeM9JbchxgwGOlO"  # Name: Reimbursement/Transaction Link
            reimbursement_transaction_amount = "fldMdawKVgVOOjlTT"  # Name: Reimbursement/Transaction Amount
            rsvp_form_sent = "flddtApxrKX4EBTUf"  # Name: RSVP Form Sent
            amount_needed = "fldWJ5D7VAIsiZydk"  # Name: Amount Needed
            roommate_form_link = "fldKDcYpRxZPYUgN2"  # Name: Roommate Form Link
            do_you_need_to_take_the_1_p_m_ferry_from_roommate_form_link = "fldl09n9yR2KpoDfL"  # Name: Do you need to take the 1 p.m. ferry? (from Roommate Form Link)
            briefly_describe_your_situation_departing_from_roommate_form_link = "fld7rLXEto7S7CUYF"  # Name: Briefly describe your situation (Departing) (from Roommate Form Link)
            departing_terminal_from_roommate_form_link = "fld6NHFbHCWCgSnPB"  # Name: Departing Terminal (from Roommate Form Link)
            outbound_flight_number_from_roommate_form_link = "fldn5Sy70OkzRhrV6"  # Name: Outbound flight number (from Roommate Form Link)
            time_of_departure_from_roommate_form_link = "fld7zQk8PTwHfJGuV"  # Name: Time of departure (from Roommate Form Link)
            after_the_event_i_would_like_to_from_roommate_form_link = "fldyvoMsw7UeYmVRw"  # Name: After the event, I would like to: (from Roommate Form Link)
            needs_accommodations_aug_11_from_roommate_form_link = "fldejF3hkyHrJ3EQv"  # Name: Needs Accommodations Aug 11 (from Roommate Form Link)
            will_you_be_able_to_make_the_5_p_m_ferry_from_roommate_form_link = "fldrlylH9QOZIrwzG"  # Name: Will you be able to make the 5 p.m. ferry? (from Roommate Form Link)
            briefly_describe_how_and_where_you_will_get_to_boston_from_roommate_form_link = "fldKLjSTgcXf7ZdTz"  # Name: Briefly describe how and where you will get to Boston (from Roommate Form Link)
            arriving_terminal_from_roommate_form_link = "fldIfA5C9PIx1VBQU"  # Name: Arriving Terminal (from Roommate Form Link)
            inbound_flight_number_from_roommate_form_link = "fldMbol4AJNmJKzOs"  # Name: Inbound flight number (from Roommate Form Link)
            estimated_time_of_arrival_from_roommate_form_link = "fldfeZzVIBfVXnQrW"  # Name: Estimated time of arrival (from Roommate Form Link)
            i_will_not_be_arriving_at_boston_logan_international_airport_from_roommate_form_link = "fldM5spOy4QvFpIN4"  # Name: I will not be arriving at Boston Logan International Airport (from Roommate Form Link)
            upon_arrival_i_would_like_to_from_roommate_form_link = "fldvGh2vopUpKpUa0"  # Name: Upon arrival, I would like to (from Roommate Form Link)
            needs_accommodations_aug_7_from_roommate_form_link = "fld9vQFqnpAKELjjK"  # Name: Needs Accommodations Aug 7 (from Roommate Form Link)
            additional_dietary_restriction_allergy_info_from_roommate_form_link = "fldEfs5fpEB5zewyb"  # Name: Additional Dietary Restriction/Allergy Info (from Roommate Form Link)
            severe_allergy_from_roommate_form_link = "fldY2Ky6YU9AG3nmA"  # Name: Severe Allergy (from Roommate Form Link)
            custom_allergy_from_roommate_form_link = "fld4Lj0nywb7S9iNf"  # Name: Custom Allergy (from Roommate Form Link)
            food_allergies_from_roommate_form_link = "fld6xyqShQyjHlnOu"  # Name: Food Allergies (from Roommate Form Link)
            custom_dietary_restriction_from_roommate_form_link = "fldBGdX8RaMdZuUwU"  # Name: Custom Dietary Restriction (from Roommate Form Link)
            dietary_restrictions_from_roommate_form_link = "fldeta09l4N9MbrJY"  # Name: Dietary Restrictions (from Roommate Form Link)
            action_trigger_logistics_email = "fldJmd4bwpUdsSwMD"  # Name: action - trigger_logistics_email
            staff = "fldLa5WoghBnFBVo0"  # Name: Staff
            custom_gender_from_roomates = "fldSIp4QLOt7o98cj"  # Name: Custom Gender (from Roomates)
            hcb_status = "fldL3XNgPleg2dRKT"  # Name: HCB Status
            wise_user_id = "fld6OppGUzf61hqZN"  # Name: Wise User ID
            wise_transfer_id = "fldMAKveYsXN1g9wT"  # Name: Wise Transfer ID
            probably_fraud = "fld92X6xgVRqDTVKL"  # Name: Probably Fraud
            looks_good = "fld6dFfSqLAsvlLfo"  # Name: Looks Good
            transaction_notes = "fldUpdNrvHOjYlFbr"  # Name: transaction_notes
            roommate_form = "fld0gnKTQmabX9jxf"  # Name: Roommate Form
            flights = "fldWmCIogsvQl3Nli"  # Name: Flights
            finished_hours = "fldW9071QhP4LGiHn"  # Name: Finished Hours
            on_island = "fldaGAebbnFaTEdm3"  # Name: On Island
            orph_plushies = "fld1OQjRBbBrk64Z5"  # Name: Orph Plushies
            slack_id_for_ping = "fldF85cNGdZZgJKG1"  # Name: slack id for ping
            day_of_prizes_form_link = "fldU7ynnx5eQisyko"  # Name: Day-of prizes form link
            additional_info_from_day_of_prizes_form_link = "fld0FWmBFHNspg43d"  # Name: Additional Info (from Day-of prizes form link)
            received_prize_from_day_of_prizes_form_link = "fld4ncM1RAivXcUBM"  # Name: Received Prize (from Day-of prizes form link)
            num_prizes_owed = "fldUs2ZOYkgBr0Ppc"  # Name: Num Prizes Owed
            num_prizes_fulfilled = "fldKB1HZsjR4AzsQn"  # Name: Num Prizes Fulfilled
            num_prizes_need_fulfillment = "fldIAQQb4XHM4tQ0j"  # Name: Num Prizes Need Fulfillment
            reviewer = "fldn7ByAZGU5CNRqx"  # Name: Reviewer
            owed_hoodie = "fldjUcpCXYjNTDEIK"  # Name: Owed Hoodie
            fudge_owed = "fldcPUwS883Gw7j6T"  # Name: Fudge Owed
            hoodie_size = "fldujtJEQv8jJpfcj"  # Name: Hoodie Size


    class highway:
        """IDs for Base 'highway' (ID: appuDQSHCdCHyOrxw)"""
        BASE_ID = "appuDQSHCdCHyOrxw"

        class rsvps:
            """IDs for Table 'rsvps' (ID: tblhGTc3WX9nYzU18)"""
            TABLE_ID = "tblhGTc3WX9nYzU18"

            email = "flduP5J737EBLvvbk"  # Name: email
            invited_to_slack = "fldkfyVH8J1qkmZbO"  # Name: invited_to_slack
            welcome_message_sent = "fldFIleT1Rf1B8b5N"  # Name: welcome_message_sent
            dm_error = "flduZHuUw19rIajXp"  # Name: dm_error
            birthday = "fldJRYzfImVmNeS9c"  # Name: birthday
            sticker_request_birthday = "fldud8kjykhWtjApx"  # Name: sticker_request_birthday
            available_birthday = "fldneqipow42yzySz"  # Name: available_birthday
            sticker_request = "fldMVkYiW3NNW4qNX"  # Name: sticker_request
            age = "fldTHAuLbNyDCYDdr"  # Name: age
            source = "fldSaQbhApCRWu1Mz"  # Name: source
            url_params = "fldDn8Y6HWI9Ekqll"  # Name: url_params
            loops_highway_pre_rsvp_at = "fldWlrEOmkdRFj7Hl"  # Name: Loops - highwayPreRsvpAt
            record_id = "fldYojFZSkbcUw43e"  # Name: Record ID
            created_at = "fldqIVKU2PGwXhqzJ"  # Name: Created At
            send_github_email = "fldhhfdejpkQMbLoL"  # Name: send_github_email
            was_at_kickoff = "fldVpS0j4d1cOT0MH"  # Name: was at kickoff


    class athena_award:
        """IDs for Base 'athena_award' (ID: appwSxpT4lASsosUI)"""
        BASE_ID = "appwSxpT4lASsosUI"

        class registered_users:
            """IDs for Table 'registered_users' (ID: tblIk0A5f9eqSng1h)"""
            TABLE_ID = "tblIk0A5f9eqSng1h"

            email = "fld0TaaawpieJ9G2A"  # Name: email
            team = "fldi2PJ5Q2pnm07fB"  # Name: team
            status_change_dm_sent = "fldOk0pb1enRYmYLs"  # Name: status_change_dm_sent
            role = "fldQWhQF9Jdo8Sb6Y"  # Name: role
            slack_id = "fldDAgtj5tJnuK6cm"  # Name: slack_id
            track = "fldduIOpBro5oKbdL"  # Name: track
            display_name = "flda5W7GQQ3hoRWEr"  # Name: display_name
            self_reported_partners_from_email_slack_invites = "fldBsOjnM2x6nd9nP"  # Name: self_reported_partners (from Email Slack Invites)
            self_reported_partners_onboarding = "fldYtMpblMK26c6Ns"  # Name: self_reported_partners_onboarding
            points = "fld782uY9yKgq3qcN"  # Name: points
            total_time_approved_projects = "fldFJqzcq3PhqhGz0"  # Name: total_time_approved_projects
            artifacts = "fldxx7cJTdiKZ0fDz"  # Name: artifacts
            hackathon_codes = "fldtdzeYRpQMmaMu5"  # Name: hackathon_codes
            hackathons = "fldqXDbPMxvL98a3i"  # Name: hackathons
            hack_clubbers = "fldaNQTyoCfE7IVFA"  # Name: Hack Clubbers
            record_id = "fldYyDAL5HpFr0mbN"  # Name: record_id
            hashed_token = "fldpTp8vdsryYVte6"  # Name: hashed_token
            registered = "fld7RHGzEfOc5OJJz"  # Name: registered
            projects = "fldBRcF2KqPVJdvdS"  # Name: projects
            duration_from_projects = "fldm6vhWLZOctIlIU"  # Name: duration (from projects)
            ysws_project_submission = "fldXnJWsOhQkl2laW"  # Name: ysws_project_submission
            address_joined_from_ysws_project_submission = "fldcdqsfjkvqxDGOP"  # Name: address_joined (from ysws_project_submission)
            approved_duration_from_projects = "fldag6JrdejDNjCAS"  # Name: approved_duration (from projects)
            unified_ysws_projects_db = "fldFl0yclGYljU6Wg"  # Name: Unified YSWS Projects DB
            hours_spent_unified_db = "fldcRUHh4REm4TyOI"  # Name: hours_spent_unified_db
            hours_spent_panathenaic_games = "fldyCFRjGB7sGMMJi"  # Name: hours_spent_panathenaic_games
            hackatime_set_up_at = "fld1X9TIKhVgP0P4I"  # Name: hackatime_set_up_at
            orders = "fldxu4NA7YMtY9oHJ"  # Name: Orders
            phone_number_from_orders = "fld1euXABRRXI92Fg"  # Name: phone_number (from Orders)
            force_refresh_ysws_projects = "fldRvL6FlJ7RDIwTn"  # Name: force_refresh_ysws_projects
            loops_athena_award_first_logged_in_at = "flducWTMuVh0xpXCP"  # Name: Loops - athenaAwardFirstLoggedInAt
            zapier_added_to_athena_mailing_list_at = "fldQJHbZozaH7MskV"  # Name: Zapier - Added to Athena mailing list at
            referred_users = "fldVqPyWX8ZTuPCAj"  # Name: referred_users
            email_slack_invites = "fldaofojjV18uvAN4"  # Name: Email Slack Invites
            referred_users_account_created = "fldnghkHaGhIKF7o9"  # Name: referred_users_account_created
            referred_users_registered_users_count = "fldl2x5dLU4pxox8N"  # Name: referred_users_registered_users_count
            referred_users_count = "fldKkUQ312lzdgpLD"  # Name: referred_users_count
            referred_users_registered_users_edition = "fld1Bl83LyowhNubP"  # Name: referred_users_registered_users_edition
            birthday_from_ysws_project_submission = "fldUk2PeUPG8VvOEh"  # Name: Birthday (from ysws_project_submission)
            age = "fldYAKM8AtS3pBGS0"  # Name: age
            last_name_from_ysws_project_submission = "fldD0Xq6rcjWdr9al"  # Name: Last Name (from ysws_project_submission)
            first_name_from_ysws_project_submission = "fldVVqv3at0W3jGAu"  # Name: First Name (from ysws_project_submission)
            profile_picture = "fldxLDUvCXQCDxfnr"  # Name: profile_picture
            project_unique_names = "fldxlzRtJrUWuwyKY"  # Name: project_unique_names
            approved_projects = "fldfQp5eDL8IEeVwH"  # Name: approved_projects
            zach_has_hackatime_or_submitted_athena_project = "fldMz3kFXwonzGVix"  # Name: Zach - has_hackatime_or_submitted_athena_project
            total_number_orders = "flddaNQgUnpAELGqE"  # Name: total_number_orders
            email_slack_invites_copy = "fldiDAliUsDB7EQV3"  # Name: Email Slack Invites copy
            email_slack_invites_copy = "fldxB0bFgfFQ7kO8O"  # Name: Email Slack Invites copy
            panathenaic_games = "fldElsHozezXtVsIa"  # Name: panathenaic games
            ordered_travel_stipend_money = "fldixCVcSIAlbTmvp"  # Name: ordered_travel_stipend_money
            approved_for_parthenon = "fldNsAL6B65xfd6LC"  # Name: approved for parthenon
            notes = "fld5wMQYthcOVbX1W"  # Name: notes
            send_parthenon_invite = "fldMV9GAB9mbCe3sW"  # Name: send parthenon invite
            prize_suggestions = "fldrKBwk6JDCfA9HI"  # Name: Prize Suggestions

        class email_slack_invites:
            """IDs for Table 'email_slack_invites' (ID: tblmiCs66Oy9ux6eN)"""
            TABLE_ID = "tblmiCs66Oy9ux6eN"

            email = "fld4z7buJbTKfaNwl"  # Name: email
            self_reported_partners = "fld2W473TCyAId9Eg"  # Name: self_reported_partners
            referred_by = "fldhVLEsJUZvAutKH"  # Name: referred_by
            ref = "fld4vbf8VXDBEJEdM"  # Name: ref
            utm_source = "fldrKkjeJ7DlQ5tid"  # Name: utm_source
            error = "fldTKFomRhiwIZgPx"  # Name: error
            dm_error = "fldCT4uWXH7orBz7Q"  # Name: dm_error
            welcome_message_sent = "fldol2W6BbcbxPZV8"  # Name: welcome_message_sent
            registered_user = "fldy5QsE0yYmolUpz"  # Name: registered_user
            created = "fld3OFPCqwso8TlPX"  # Name: Created
            loops_athena_award_slack_invite_requested_at = "fld7hufACh1X4tp42"  # Name: Loops - athenaAwardSlackInviteRequestedAt
            zapier_added_to_athena_mailing_list_at = "fldGAuFJmK2yb5H3v"  # Name: Zapier - Added to Athena mailing list at
            loops_athena_award_pyramid_scheme_sign_up_ref = "fldY4wcTCAIegtRFo"  # Name: Loops - athenaAwardPyramidSchemeSignUpRef

        class free_sticker_form:
            """IDs for Table 'free_sticker_form' (ID: tblBOgmyC9RVK98wD)"""
            TABLE_ID = "tblBOgmyC9RVK98wD"

            email = "fldN19TbrTnCXSngO"  # Name: Email
            first_name = "fldf3tegs4na6q0Yp"  # Name: First Name
            last_name = "fldQjTSwM4Q2CFJwB"  # Name: Last Name
            pronouns = "fldtE2kq4EsjdbIOI"  # Name: Pronouns
            git_hub_username = "fldZ9X0H5Fl2gGID3"  # Name: GitHub Username
            birthday = "fldTEJDYg9Ws6OtqY"  # Name: Birthday
            address_line_1 = "fldQ49GD41UG0gb7Q"  # Name: Address Line 1
            address_line_2 = "fldPXNCo4ckwUf9Hr"  # Name: Address Line 2
            city = "fldHsStlvMorfS9gx"  # Name: City
            state = "fldgk1AAysYHcHrpF"  # Name: State
            zip_postcode = "fldkOjR7CJeRB2EBs"  # Name: ZIP/Postcode 
            country = "flddIqe8RLyOnGKc2"  # Name: Country
            loops_athena_award_stickers_requested_at = "fldVIrRhcFEzcC8vS"  # Name: Loops - athenaAwardStickersRequestedAt
            loops_first_name = "fldEEk4v3I8MlhTQt"  # Name: Loops - firstName
            loops_last_name = "fldWp3vGALPoh24pm"  # Name: Loops - lastName
            loops_gender_self_reported = "fldndV1vBDxKiUGLo"  # Name: Loops - genderSelfReported
            loops_github_username = "fldLCS6Wq52UwkNTI"  # Name: Loops - githubUsername
            loops_special_set_full_address = "fldXckAr3vu1m1MsD"  # Name: Loops - special - setFullAddress
            theseus_letter_id = "fld65tjhaen9iv77b"  # Name: Theseus – Letter ID
            theseus_status = "fldQHZvDCbUMRdHnf"  # Name: Theseus – Status
            theseus_mailed_at = "fldUSdrzjAlXx4w2l"  # Name: Theseus – Mailed At
            theseus_received_at = "fldkxqtBALXfXzBLu"  # Name: Theseus – Received At
            theseus_postage_cost = "fldkAbCFvMOqDFDz2"  # Name: Theseus – Postage Cost
            theseus_create_letter = "fldfszoyV5xqqz2Yl"  # Name: Theseus – Create Letter
            theseus_error = "fldfyIYIf8FYo2s0z"  # Name: Theseus – Error

        class projects:
            """IDs for Table 'projects' (ID: tblZqHeeelwGkOkRr)"""
            TABLE_ID = "tblZqHeeelwGkOkRr"

            record_id = "fldcwoCVYQ9P3GdKv"  # Name: record_id
            unique_name = "fld8A7FjUiOI5Ho8M"  # Name: unique_name
            unique_name_email = "fldrwowgSdETRYNtV"  # Name: unique_name_email
            project_name = "fld6vGpatATHH7rn8"  # Name: project_name
            project_name_override = "fldCodpGWr0hiGisg"  # Name: project_name_override
            guided_ysws = "fld16dhOG3s49vzq5"  # Name: guided_ysws
            automation_guided_ysws = "fldvYjS28P2rnw9H6"  # Name: automation_guided_ysws
            hackatime_duration = "fldiMCjGxVHmafb5f"  # Name: hackatime_duration
            existing_ysws_project_hour_override = "fldYiOsaEbm0oRa8s"  # Name: existing_ysws_project_hour_override
            approved_duration = "fld4eD1QIbHookKrF"  # Name: approved_duration
            stage = "fldDeBwC0YPE69Xl3"  # Name: stage
            status = "fld8mVhD1hOom2i9i"  # Name: status
            order = "fld9YhS7dp9fWVzoo"  # Name: order
            registered_user = "fldbWcHEPieWbwaaQ"  # Name: registered_user
            email = "flddvqww48TLt7JKs"  # Name: email
            form_submitted_project = "fldis1ignLpvSF5LK"  # Name: form_submitted_project
            screenshot_from_form_submitted_project = "fld60qq9Vu1DJh32S"  # Name: Screenshot (from form_submitted_project)
            code_url = "fldBDPByuRJgVWyjw"  # Name: code_url
            playable_url = "fldnRGAfDwBt9W94m"  # Name: playable_url
            address_joined_no_name_from_form_submitted_project = "fld2iQEZHFPBS49n7"  # Name: address_joined_no_name (from form_submitted_project)
            user_consent = "fldWlAVD9AlG1NYak"  # Name: user_consent
            all_submitted_project_status = "fldFpKOTQTjnzpeZ3"  # Name: all_submitted_project_status
            all_user_unified_db_from_form_submitted_project = "fldJ3gNj9mFdrkZnM"  # Name: all_user_unified_db (from form_submitted_project)
            address_joined_from_ysws_project = "fldubS1WoqZqkxBh9"  # Name: address_joined (from ysws project)
            lat = "fldZhX8EGkWJMKRvX"  # Name: lat
            lng = "fld0AcwZhDQXhx9qS"  # Name: lng
            slack_id = "fldTrCGiaOMAVED5o"  # Name: slack_id


    class unified_ysws_db:
        """IDs for Base 'unified_ysws_db' (ID: app3A5kJwYqxMLOgh)"""
        BASE_ID = "app3A5kJwYqxMLOgh"

        class approved_projects:
            """IDs for Table 'approved_projects' (ID: tblzWWGUYHVH7Zyqf)"""
            TABLE_ID = "tblzWWGUYHVH7Zyqf"

            record_id = "fld7m7AA0teKodijc"  # Name: Record ID
            id = "fldmLazalAjZ41o0u"  # Name: ID
            email = "fldmqHE7RIvjvglfX"  # Name: Email
            referral_reason = "fld5YYWNTvtHp1xSq"  # Name: Referral Reason
            how_did_you_hear_about_this = "flditN5yjq6VG7FyS"  # Name: How did you hear about this?
            what_are_we_doing_well = "fldbIKqiQBvICSyPH"  # Name: What are we doing well?
            how_can_we_improve = "fldnstXrVNfHMQyCo"  # Name: How can we improve?
            age_when_approved = "fldAcWtAV0rzN3ZLA"  # Name: Age When Approved
            playable_url = "fld5plJTA93ugLnI2"  # Name: Playable URL
            code_url = "fldZhfNBM9GR0TR0R"  # Name: Code URL
            screenshot = "fld4vp6gwjwRQB4wM"  # Name: Screenshot
            description = "fldoLo6I6AhKO0clK"  # Name: Description
            git_hub_username = "fldNBBGaCR5oX4PAh"  # Name: GitHub Username
            address_line_1 = "fldQjH6UJfJLx2OKk"  # Name: Address (Line 1)
            address_line_2 = "fldNef7AOD2Ij7F6k"  # Name: Address (Line 2)
            city = "fldQ4BjcgP9eLo3BR"  # Name: City
            state_province = "fldIqBn7yNHYBHVtO"  # Name: State / Province
            country = "fldwnMuafGvdzPC81"  # Name: Country
            zip_postal_code = "fld2Z6AfRSA1nrOF1"  # Name: ZIP / Postal Code
            birthday = "fldTjqgv6tj7wIwJo"  # Name: Birthday
            hours_spent = "fldk901J18n06Q1pY"  # Name: Hours Spent
            override_hours_spent = "fldX6BuA83jPVMH3N"  # Name: Override Hours Spent
            override_hours_spent_justification = "fldSMvlh1LIe3m7AX"  # Name: Override Hours Spent Justification
            ysws_weighted_project_contribution = "fldO6slYG2hKx89El"  # Name: YSWS–Weighted Project Contribution
            ysws_weighted_project_author_attribution = "fldpvTcMezPwzMyRO"  # Name: YSWS–Weighted Project Author Attribution
            approved_at = "fldB6hzaH7SIz9CQi"  # Name: Approved At
            created = "fldh8rUhEKOM0uFPt"  # Name: Created
            ysws = "fldRWPZyaEPBDDz7x"  # Name: YSWS
            first_name = "fldVVfL6j9S5s2CSi"  # Name: First Name
            last_name = "fldUx3OeChK5PDBg3"  # Name: Last Name
            ysws_weighted_project_author_attribution_count = "fldAgVajme4ci52NH"  # Name: YSWS–Weighted Project Author Attribution Count
            ysws_weighted_project_contribution_per_author = "fldWcvCzG67uJoEV0"  # Name: YSWS–Weighted Project Contribution Per Author
            ysws_default_hours_per_grant = "fldszX7e87sog5S3y"  # Name: YSWS–Default Hours Per Grant
            ysws_name = "fldVa0pJbIqczqwVM"  # Name: YSWS–Name
            ysws_current_owners = "fldoP6VwW6PtWdFf2"  # Name: YSWS–Current Owners
            archive_live_url = "fld23yYoziYecDwLu"  # Name: Archive - Live URL
            archive_code_url = "fld1Xfgpcjiilk6cS"  # Name: Archive - Code URL
            archive_archived_at = "fldBuUAbjyPGuMlv6"  # Name: Archive - Archived At
            hack_clubber = "fldPzArB9uPrnjRWw"  # Name: Hack Clubber
            hack_clubber_geocoded_country = "fldDyo57k4POiIlO4"  # Name: Hack Clubber–Geocoded Country
            ysws_spot_checks = "fldm0HMxgc3oQsDNs"  # Name: YSWS Spot Checks
            geocoded_country = "fldClKvcVnM9IkQ9t"  # Name: Geocoded - Country
            geocoded_country_code = "fldaahUBdI2852lf9"  # Name: Geocoded - Country Code
            geocoded_latitude = "fldoHZxN7wdYxYpr6"  # Name: Geocoded - Latitude
            geocoded_longitude = "fldNdgSKp7JStAm6h"  # Name: Geocoded - Longitude
            geocoded_address_hash = "fldUoOUQ7s2jgHWLa"  # Name: Geocoded - Address Hash
            archive_hash = "fldIxgUiHJ4XtWmF5"  # Name: Archive - Hash
            project_mentions_links = "fld0UipcnSnWGrG0H"  # Name: Project Mentions - Links
            repo_star_count = "fldYhr34qkhdJ8qMo"  # Name: Repo - Star Count
            repo_stats_last_updated_at = "fldKm8IcRKJKY5mat"  # Name: Repo - Stats Last Updated At
            repo_language = "fldHseqUz3wQtu0Ul"  # Name: Repo - Language
            repo_exists = "fldrDVqbGZJXLpd9G"  # Name: Repo - Exists?
            ysws_project_mentions_searches = "fldtDxmAsUu6FB8bu"  # Name: YSWS Project Mentions - Searches
            ysws_project_mentions_search_count = "fldQqO4G8xEHN64yh"  # Name: YSWS Project Mentions - Search Count
            ysws_project_mentions_last_search_links_found = "fldYxaMoN8RemVRbG"  # Name: YSWS Project Mentions - Last Search, # Links Found
            ysws_project_mentions_estimated_search_cost = "fldDMOqywU1ytG5JO"  # Name: YSWS Project Mentions - Estimated Search Cost
            ysws_project_mentions_5_links_on_last_search = "fldbAEGX0vsbdhXrZ"  # Name: YSWS Project Mentions - ≥5 Links on Last Search?
            ysws_project_mentions_no_searches_and_20_repo_stars = "fld6uNVuMSJ0f20Xt"  # Name: YSWS Project Mentions - No Searches And ≥20 Repo Stars
            ysws_project_mentions_repo_stars_at_last_search = "fldJ49PEMPDTT8MqH"  # Name: YSWS Project Mentions - Repo Stars At Last Search
            ysws_project_mentions_last_search_at = "fld9XaVArOhSMN1ZX"  # Name: YSWS Project Mentions - Last Search At
            ysws_project_mentions_5_repo_stars_since_last_search_and_72_hours_passed = "fld8DDjp1jZtM1Psh"  # Name: YSWS Project Mentions - ≥5 Repo Stars Since Last Search And 72 Hours Passed
            ysws_project_mentions_project_wants_search = "fldooCX18uLnxpcAp"  # Name: YSWS Project Mentions - Project Wants Search?
            ysws_project_mentions_reddit_upvotes = "fldIeUwZRLnUPfRSU"  # Name: YSWS Project Mentions - Reddit Upvotes
            ysws_project_mentions_hacker_news_points = "fld9owikn8oFm3yWZ"  # Name: YSWS Project Mentions - Hacker News Points
            ysws_project_mentions_links_found = "fldXr6S0NaprCe1Os"  # Name: YSWS Project Mentions - # Links Found
            ysws_project_mentions_1_search_but_2_searches = "fldwGVU8rqVt6ZvaF"  # Name: YSWS Project Mentions - ≥1 Search, But <2 Searches?
            ysws_project_mentions_total_engagement_count = "fldIpjT3j51aj5rs6"  # Name: YSWS Project Mentions - Total Engagement Count
            ysws_project_mentions_search_count_copy = "fld0tiao8RJzjPk5e"  # Name: YSWS Project Mentions - Search Count copy
            ysws_project_mentions_weighted_points = "fldxynj95VVOg0t3k"  # Name: YSWS Project Mentions - Weighted Points
            ysws_project_mentions_top_link = "fldM6SIIXbnkWY3hk"  # Name: YSWS Project Mentions - Top Link
            state = "flduHp6cOwETXTRnr"  # Name: State 
            county_centralizing = "fldu7bexqqfq3KoZ0"  # Name: County - Centralizing

        class ysws_programs:
            """IDs for Table 'ysws_programs' (ID: tblrGi9RARJy1A0c5)"""
            TABLE_ID = "tblrGi9RARJy1A0c5"

            name = "fldZgYSSBqqxIPmhR"  # Name: Name
            current_owners = "fldQ44zr4gy8R7h6e"  # Name: Current Owners
            hcb = "fld972PVFuuSpAPY5"  # Name: HCB
            cost_per_hour = "fldwSYLyCEVfHhkwK"  # Name: Cost Per Hour
            weighted_projects_this_month = "flddWQbhmy3oytww2"  # Name: Weighted Projects This Month
            weighted_projects_2025 = "fldPVrNUdWKGiqv68"  # Name: Weighted Projects–2025
            weighted_total = "fldgfs70478BwFFBj"  # Name: Weighted–Total
            unweighted_total = "fldPV2UvmrSrML24w"  # Name: Unweighted–Total
            nps_score = "fldrWoUZtmFe3BIEF"  # Name: NPS Score
            nps_response_count = "fldpOPSDZE1B9G7Kc"  # Name: NPS–Response Count
            nps_median_estimated_hours = "fldsa0oY9TT5DE5hH"  # Name: NPS–Median Estimated Hours
            average_hours_per_grant = "fldZvx6LJBp9xVELO"  # Name: Average Hours Per Grant
            airtable_id = "fld7PmAuqC5hteumO"  # Name: Airtable ID
            slack_icon = "fldurCZZKmQAovBiT"  # Name: Slack Icon
            icon_last_hash = "fldomRhDRIk3yHRNr"  # Name: Icon – Last Hash
            icon_cdn_link = "fldP1FnevuLHRc2aP"  # Name: Icon – CDN Link
            total_spent_from_hcb_fund = "fldZXeZNxFeAhZEt0"  # Name: Total Spent From HCB Fund
            need_to_add_postage_cost = "fldueuLMJtGaaz5O3"  # Name: Need To Add Postage Cost?
            estimated_cost_per_package = "fldjmQGftCRqGfp6J"  # Name: Estimated Cost Per Package
            estimated_pirate_ship_spend = "fldyVNaPS0zJTuuGE"  # Name: Estimated Pirate Ship Spend
            total_spend = "fldpQvbD1r4g1tnBx"  # Name: Total Spend
            total_sign_ups = "fldqJF8rDeJUMK2Jp"  # Name: Total Sign-Ups
            total_sign_ups_new_to_hack_club = "fldgMET7U2QCAh4KN"  # Name: Total Sign-Ups New To Hack Club
            sign_up_stats_override_prefix = "fldLenSCDJthFje4k"  # Name: Sign-Up Stats–Override Prefix
            cost_per_sign_up_new_to_hack_club_in_excess_of_5_hr_limit = "fldvFG8heXjNc3ob2"  # Name: Cost Per Sign Up New To Hack Club In Excess of $5/hr Limit
            over_budget = "fldIj9DfI1qAAXsOZ"  # Name: Over Budget
            unweighted_projects_2025 = "fldEgwrScoA7vDl5J"  # Name: Unweighted Projects–2025
            weighted_projects_this_past_7_days_rolling = "fldTXgejdYHGzmuqI"  # Name: Weighted Projects This Past 7 Days (rolling)
            unweighted_projects_this_month = "flduPo2OfV0dXzcxe"  # Name: Unweighted Projects This Month
            unweighted_projects_this_past_7_days_rolling = "fld0tcjjvv27MjgVC"  # Name: Unweighted Projects This Past 7 Days (rolling)
            unweighted_projects_2024 = "fldaF2tMyTf7bmwBP"  # Name: Unweighted Projects–2024
            weighted_projects_2024 = "fldN79ypYWBbJfjYs"  # Name: Weighted Projects–2024
            nps_promoter = "fldPlyrIvIRBHBsRw"  # Name: NPS–Promoter %
            nps_detractor = "fldhcVd4h9ZvkUnR3"  # Name: NPS–Detractor %
            grants_awarded = "fldw177830TOPdm5X"  # Name: Grants Awarded
            nps = "flduxo3A7RNi6Mv5H"  # Name: NPS
            average_weight = "fldgEggvCPyiTCmWX"  # Name: Average weight
            weighted_projects_jan_2025 = "fldpGZvT9OHb1Cn4g"  # Name: Weighted Projects–Jan 2025
            month_override = "fldCSuoy2Os4FkfAq"  # Name: Month Override
            avg_per_month = "fldgQX4bmCd4MRs3x"  # Name: Avg per month
            first_grant = "fldsAQSZiyZNPe3t6"  # Name: First grant
            last_grant = "fldM5xEaX53aPHgT4"  # Name: Last grant
            months = "fldCwUHh5LNOjEUaL"  # Name: Months
            ysws_project_mentions_total_weighted_points = "flddUBwt0AveKXJnQ"  # Name: YSWS Project Mentions - Total Weighted Points
            temp_bounty_per_grant = "fldz7tTLnxrg3F3sq"  # Name: temp - Bounty per grant

        class ysws_authors:
            """IDs for Table 'ysws_authors' (ID: tblRf1BQs5H8298gW)"""
            TABLE_ID = "tblRf1BQs5H8298gW"

            name = "fldlE95RqYyq8DJW4"  # Name: Name
            slack_url = "fldb79ToRvdcXeqze"  # Name: Slack URL
            slack_id = "fldojyNhEYyuZSo35"  # Name: Slack ID
            hcb_budget_fund = "fldStVwvzbzx7Ambm"  # Name: HCB Budget Fund
            weighted_grants_this_month = "fldPfA6UkbmKoKPE5"  # Name: Weighted Grants This Month
            weighted_grants_2025 = "fldhG2hMtQ73KZ0qq"  # Name: Weighted Grants–2025
            weights_grants_june_2025 = "fld6D3uHxMqmO9Bp7"  # Name: Weights Grants–June 2025
            weights_grants_feb_2025_copy = "fldjI1DCwRYUTlMUU"  # Name: Weights Grants–Feb 2025 copy
            weights_grants_jan_2025 = "fld3Gdn4SFPUNTnuK"  # Name: Weights Grants–Jan 2025
            weights_grants_dec_2024 = "fldNxopvpzYH3FOjk"  # Name: Weights Grants–Dec 2024
            weights_grants_nov_2024 = "fldxJPpCMOsEmDoVx"  # Name: Weights Grants–Nov 2024
            weights_grants_oct_2024 = "fldBOI0n9BtDxHLm0"  # Name: Weights Grants–Oct 2024
            weighted_grants_last_month = "fldFfOt7PBDs7zc9Z"  # Name: Weighted Grants Last Month
            weights_grants_sep_2024 = "fldHARrmhE7Q19lzu"  # Name: Weights Grants–Sep 2024
            weighted_grants_2024 = "fld2wxB7twgaNTPBZ"  # Name: Weighted Grants–2024
            current_ysws_programs = "fldrUpZPQmKClNouO"  # Name: Current YSWS Programs
            weighted_grants_total = "fldllCyssGiFPi5mS"  # Name: Weighted Grants–Total
            attributed_grants = "fldM4SHI9hXry0pPC"  # Name: Attributed Grants
            weights_grants_mar_2025_copy = "fldkpZAqxuLJnu9do"  # Name: Weights Grants–Mar 2025 copy
            weighted_grants_excluding_shared = "fld4p6J1NvBlAK2J1"  # Name: Weighted Grants (excluding shared)
            usd_for_weighted_grants = "fldemaqXRN95KSs8S"  # Name: USD for Weighted Grants

        class nps:
            """IDs for Table 'nps' (ID: tblQpkS0I9V2ixBD0)"""
            TABLE_ID = "tblQpkS0I9V2ixBD0"

            on_a_scale_from_1_10_how_likely_are_you_to_recommend_this_ysws_to_a_friend = "fldWbHGO7UQUkYtYu"  # Name: On a scale from 1-10, how likely are you to recommend this YSWS to a friend?
            ysws = "fldzNjiMkRtN2V7Y0"  # Name: YSWS
            email_optional_for_prize = "fldylKfsw54T6Quvf"  # Name: Email (optional, for prize)
            what_are_we_doing_well = "fldmmrs0b33yjhrCP"  # Name: What are we doing well?
            how_can_we_improve = "fldcl0lviiqpaFfGZ"  # Name: How can we improve?
            how_many_hours_do_you_estimate_you_spent_on_your_project = "fldmlrjb5GnMZrl4Q"  # Name: How many hours do you estimate you spent on your project?
            custom_fields = "fldISC6kkMwvS67bD"  # Name: Custom Fields
            record_created_at = "fldAVEMxQbXCe7dnU"  # Name: Record Created At
            nps_category = "fldnAF7XOL4FjZQSj"  # Name: NPS Category
            prize_winner = "fldxFR7tBNzQBMpFT"  # Name: Prize Winner?
            override_created_at = "fldXSYurztepXkeCc"  # Name: Override Created At
            created_at = "fldr50yArbZc0w3YL"  # Name: Created At

        class ysws_project_mentions:
            """IDs for Table 'ysws_project_mentions' (ID: tbl5SU7OcPeZMaDOs)"""
            TABLE_ID = "tbl5SU7OcPeZMaDOs"

            id = "fldizbzyosiUHlaf5"  # Name: ID
            ysws_approved_project = "fldWCs3fjJ6Tnw10T"  # Name: YSWS Approved Project
            project_url = "fldRqywkrPXW3wtpA"  # Name: Project URL
            date = "fldEIIGc5hs9EQmmb"  # Name: Date
            source = "fldeNhLPVabss8YAq"  # Name: Source
            headline = "flds6DCPxUVqNSBqH"  # Name: Headline
            url = "fldew9uAD9qtGruhE"  # Name: URL
            archive_url = "fldlB2GQfdpVb70Mm"  # Name: Archive URL
            engagement_count = "fldYAciVBuduGXROY"  # Name: Engagement Count
            engagement_type = "fldY9PDQGKoXpqJTz"  # Name: Engagement Type
            mentions_hack_club = "fldHqMUIH4Ep8YiAc"  # Name: Mentions Hack Club?
            published_by_hack_club = "fld42Wo1xHrraPCI0"  # Name: Published by Hack Club?
            full_json = "fldBj7MzoOGi9nq8p"  # Name: Full JSON
            link_found_at = "fld4gm2Xez4mBoiK3"  # Name: Link Found At
            ysws_project_mention_searches = "fldN6tSGcdHKBGaME"  # Name: YSWS Project Mention Searches
            ysws_from_ysws_approved_project = "fldJPnugEv9PwdzA4"  # Name: YSWS (from YSWS Approved Project)
            weighted_engagement_points = "fldUAPNuojwY2sFd6"  # Name: Weighted Engagement Points
            record_id = "fldLMXyX9yAQLups7"  # Name: Record ID

        class ysws_project_mention_searches:
            """IDs for Table 'ysws_project_mention_searches' (ID: tblfU7k0cgzysujpH)"""
            TABLE_ID = "tblfU7k0cgzysujpH"

            id = "fldY7j6t3UxmEThlN"  # Name: ID
            created_at = "fldJwCqbm4lSx4Ucw"  # Name: Created At
            project = "fldgFAh5zUBHlTuia"  # Name: Project
            code_url = "flde9I9mNZKvYX0GE"  # Name: Code URL
            found_project_mentions = "fldYseJ4gHgnpmj3v"  # Name: Found Project Mentions
            links_found = "fldACN2e7BR5eJpVB"  # Name: # Links Found
            output_json = "fldNDXvfes4mM0Ela"  # Name: Output JSON
            full_output_log = "fldGSqjPjBrBTZ9mU"  # Name: Full Output Log
            prompt = "fld9VSGBsp8EGDtH3"  # Name: Prompt
            model = "fldkkknv2j8H7w6gm"  # Name: Model
            runtime_h_mm_ss = "fldfypNKOUnOMfNyH"  # Name: Runtime (h:mm:ss)
            non_cached_input_tokens = "fldCUHDrd6r2EKQGh"  # Name: Non-Cached Input Tokens
            cached_input_tokens = "fldiGAB6gdyVSpEBF"  # Name: Cached Input Tokens
            output_tokens = "fldue08EOkmkiViOz"  # Name: Output Tokens
            estimated_cost = "fldPY7wVai7FUZuBr"  # Name: Estimated Cost
            estimated_non_cached_input_cost_gpt_5 = "fldm3r9OZKnQumdpc"  # Name: Estimated Non-Cached Input Cost (GPT-5)
            estimated_cached_input_cost_gpt_5 = "fldrVFkuHIuL1LkQF"  # Name: Estimated Cached Input Cost (GPT-5)
            estimated_output_cost_gpt_5 = "fldbTyDX3a1KtqXvt"  # Name: Estimated Output Cost (GPT-5)

        class ysws_spot_checks:
            """IDs for Table 'ysws_spot_checks' (ID: tbltWKtnaXRVJDEo3)"""
            TABLE_ID = "tbltWKtnaXRVJDEo3"

            name = "fldklFByqYPGhL0Lt"  # Name: Name
            project = "fld8L5aLfa95FfqRE"  # Name: Project
            ysws = "fldxWGwk7aV0Nnsn2"  # Name: YSWS
            assessment = "fldHje5936m66CNQX"  # Name: Assessment
            notes_for_ysws_authors = "fldBx3JM2ucdppfD2"  # Name: Notes For YSWS Authors
            reviewer_name = "fldXvvanOukkGItAo"  # Name: Reviewer Name
            time_spent_on_review_mm_ss = "fldglMzxS6yQHJIZ4"  # Name: Time Spent On Review (MM:SS)
            duration_start_time = "fld4r0t7YiRSgKc42"  # Name: Duration - Start Time
            duration_end_time = "fld6gtQqSmho4FHRJ"  # Name: Duration - End Time
            reviewer_email = "fldt0CZmyLwdRawcw"  # Name: Reviewer Email
            reviewer_slack_id = "fldtMnod5KQMBlA5S"  # Name: Reviewer Slack ID
            reviewer_avatar_url = "fldF9dYCPtXle4fiK"  # Name: Reviewer Avatar URL
            created_at = "fldqVswJVCJbp1Nmd"  # Name: Created At
            spot_check_session = "fldNZse2GeyPDnWqm"  # Name: Spot Check Session

        class ysws_spot_check_sessions:
            """IDs for Table 'ysws_spot_check_sessions' (ID: tblJCBhT1pYJcrQjV)"""
            TABLE_ID = "tblJCBhT1pYJcrQjV"

            name = "fldfcOPz083Cmcoct"  # Name: Name
            filters = "fldRkBkXmeleXm42h"  # Name: Filters
            sampling_strategy = "fldJcbSZQimehm5BC"  # Name: Sampling Strategy
            creator_name = "fldWujo41rCLMQoAL"  # Name: Creator Name
            creator_slack_id = "fldjmhk2s0GjLAEvX"  # Name: Creator Slack ID
            creator_email = "fldtYXhgT0XW68ZJ9"  # Name: Creator Email
            creator_avatar_url = "fld65sbZqOcNtdOAZ"  # Name: Creator Avatar URL
            start_time = "fld8r59hCI2ApspVh"  # Name: Start Time
            end_time = "fldFNstKhvejUgdrb"  # Name: End Time
            ysws_spot_checks = "fld2OIOCpgU2MMtxT"  # Name: YSWS Spot Checks


# fmt: on